export type ChangelogEntry = {
  version: string;
  title: string;
  changes: string[];
};

/**
 * Historial de cambios en lenguaje simple (para cualquier usuario, sin tecnicismos).
 * Más nuevo primero. Se muestra al tocar la versión en Configuración.
 */
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "1.0.10",
    title: "DarkMoney estrena look",
    changes: [
      "DarkMoney estrena look. El fondo pasa de azulado a un gris cálido, los montos se leen de un vistazo porque los céntimos ya no compiten con la cifra, y en la lista de movimientos caben cuatro filas más por pantalla sin que la letra se haga más chica.",
      "El inicio va directo al grano: se fueron los textos que describían la pantalla antes de mostrarla, así que ves tus cifras apenas abres.",
      "Cuando no hay nada previsto para la semana, la app te lo dice con palabras en vez de mostrarte ceros que parecían un error de carga.",
      "El gráfico de cierre de mes ahora se lee como un recorrido: cada barra arranca donde terminó la anterior, así ves qué te sube y qué te baja el saldo.",
      "En el historial del año, los meses en los que gastaste más de lo que entró bajan por debajo de la línea. Un mal mes se ve de un golpe.",
      "Elegir entre vista simple y avanzada se mudó a Configuración: se elige una vez y se recuerda, en vez de ocupar sitio en cada pantalla.",
      "Cómo te habla el asistente del inicio también se elige una vez en Configuración, en lugar de preguntártelo en cada pantalla.",
      "En la pestaña de Salud, en vez de un texto que te explica el problema, ahora hay un botón que te lleva directo a los movimientos sin categoría para arreglarlos.",
      "Tus contactos ahora entran más por pantalla, y ya no repiten la categoría dos veces en la misma línea.",
      "Los colores ahora significan una sola cosa cada uno: verde es plata que entra, y los gastos ya no se ven como si fueran un error. El asistente tiene su propio color, para que distingas lo que él opina de lo que dicen tus cuentas.",
      "Cada día de la lista de movimientos te dice de un vistazo cuánto entró o salió ese día.",
      "La pantalla que ves mientras la app abre ya no es azul: usa el mismo gris cálido que todo lo demás, así que abrir DarkMoney ya no da un salto de color.",
      "La barra de abajo ya no tapa lo último de cada lista, y con la letra del sistema en grande dejó de cortarse.",
      "Al bloquear y desbloquear el teléfono, la app ya no te muestra la pantalla de inicio de sesión: sigues donde estabas.",
      "Si guardas algo apenas abres la app y la conexión todavía va lenta, DarkMoney espera a que el servidor termine antes de darte por perdido: ya no te avisa que no sabe si se guardó cuando en realidad sí quedó registrado.",
      "El menú \"Más\" ahora cabe entero sin desplazarse, y cada opción te dice lo que tiene dentro: cuánto te cuestan al mes tus suscripciones, cuántas categorías tienes, a cómo está el dólar.",
      "Configuración dejó de empezar con un formulario largo. Tus datos y tu foto tienen ahora su propia pantalla, y las preferencias se ven todas juntas apenas entras.",
      "Elegir tu moneda base ya no es buscar entre veintidós botoncitos: es una línea que dice cuál tienes y abre la lista al tocarla.",
      "En Detección automática ya no hay que elegir cuenta app por app: viene puesta tu cuenta principal y se cambia solo si quieres otra.",
      "Las opciones del menú \"Más\" ahora vienen agrupadas: lo que reclama tu atención, lo que se repite cada mes y lo que se configura una vez.",
      "Cuando un filtro esconde todo lo que tienes, la app ya no te dice \"sin resultados\" como si no hubiera nada: te dice cuántos tienes y te ofrece quitar el filtro.",
      "En Suscripciones, el total del mes ahora aclara que las pausadas no están sumadas, así que la cuenta ya no parece mal hecha.",
      "Arreglado un error de cuentas: una deuda que alguien compartió contigo se sumaba a lo que te deben en vez de a lo que debes. Por eso podías ver \"No debes nada\" teniendo una deuda justo debajo. Afectaba también a las cifras del inicio.",
      "Registrar una deuda o un préstamo cabe ahora en una pantalla. Antes eran dieciocho campos repartidos en tres pantallas de scroll para cuatro que son obligatorios; los demás viven en \"Más detalles\", que se abre solo si lo necesitas. Y dice \"Me deben\" y \"Yo debo\", que es como lo piensa uno.",
      "El detalle de una deuda o préstamo abre mostrando lo que pasó. Antes el historial arrancaba filtrado por \"mes actual\" y te decía que no había nada, aunque tuvieras veinte movimientos guardados. Y cada línea te dice con cuánto quedó la cuenta después de ella.",
      "El estado de cuenta en PDF se puede leer hoja por hoja: la segunda página ya no empieza en el aire, dice de cuánto venía el saldo. Cada línea encabeza con lo que vendiste o pagaste, no con el nombre técnico del movimiento, y el saldo pendiente es lo primero que ve quien lo recibe.",
      "En el detalle de una deuda o préstamo ahora ves el plan al lado de lo que de verdad se pagó: si acordaron 300 y te pagaron 320, se ven los dos números juntos. Los 20 de más no cambian las cuotas que pactaron, se descuentan de la última.",
      "Al crear una deuda o préstamo, la app te ofrece invitar a la otra persona cuando ya está guardada — y no manda nada hasta que toques Enviar. Antes el correo salía solo al guardar, sin que pudieras revisarlo.",
      "Nuevo: puedes acordar los pagos uno por uno. Si tu acuerdo es \"100 en setiembre, 150 en octubre y 200 de ahí en adelante\", lo escribes tal cual y la app calcula el resto hasta terminar el saldo — incluida la última cuota, que casi nunca es igual a las otras. Antes solo se podían poner cuotas iguales.",
      "Crear una suscripción ya no es una pantalla larguísima: pide el nombre, el monto, cada cuánto se cobra y cuándo es el próximo, y todo lo demás está en \"Opcionales\" por si lo necesitas.",
      "Ya no te pide tres fechas para una suscripción. Solo la del próximo cobro, que es la única que el sistema usa; el inicio y el fin quedaron como opcionales.",
      "Crear una cuenta ya no empieza por dos filas de botones que se cortan por el borde: tipo, institución, moneda y apariencia son cuatro líneas que abren su lista, y el botón te dice qué falta mientras no le pongas nombre.",
      "Crear una categoría empieza por el nombre. Los íconos y colores pasaron a una línea que abres si quieres cambiarlos, en vez de ocupar media pantalla antes del único campo obligatorio.",
      "Desapareció el campo \"Orden\" de las categorías, que pedía un número sin explicar para qué servía. Ahora se acomoda solo.",
      "Elegir moneda, cuenta, categoría o contacto en cualquier formulario ya no es una fila de botones que se corta por el borde: es una lista que se abre y se puede buscar.",
      "Los botones de guardar ahora te dicen qué falta —\"Falta el monto\"— en vez de quedarse apagados sin explicar por qué.",
      "La pestaña Salud dejó de ser interminable. Antes te daba cuatro porcentajes distintos de \"confianza\" sin decirte cuál mirar; ahora hay uno solo, con lo que falta para subirlo.",
      "En Salud, lo primero que ves por revisar son los movimientos sin contraparte: eran los más numerosos y estaban escondidos. Y los que no tienen categoría te dicen cuánto pesan de tu gasto.",
      "La proyección del cierre de mes ya no está repetida en dos pestañas: vive solo en Flujo, que es donde la buscas.",
      "Lo de \"cómo aprende DarkMoney\" se mudó a Configuración › Acerca de. Estaba en medio de tus finanzas ocupando media pantalla, y no era algo que pudieras cambiar.",
      "Registrar un movimiento es mucho más rápido: pones el monto y la cuenta y ya puedes guardar. Antes te obligaba a pasar por una pantalla entera de campos que no eran obligatorios.",
      "Los detalles —categoría, contraparte, notas, comprobantes— siguen ahí, pero ahora entras solo si los necesitas.",
      "El botón de guardar ya no se esconde al final: está fijo abajo desde que abres el formulario.",
      "El monto se escribe como en el resto de la app: S/ 21.30, no \"PEN 21.3\".",
      "En una transferencia entre tus cuentas ya no se pinta una mitad en rojo como si hubieras perdido plata: es la misma plata cambiando de bolsillo, y la app ahora te lo dice.",
      "Las sugerencias de la app ya no anuncian que están pensando ni te dicen que no encontraron nada: aparecen solo cuando hay algo que proponer, pegadas al campo que van a cambiar, y te dan la razón en palabras —\"Porque corregiste esto antes\"— en vez de un porcentaje que no sabías con qué comparar.",
      "En los detalles del movimiento, elegir categoría o contraparte ya no es una fila de botones que se corta por el borde: es una lista que se abre y se puede buscar.",
      "La fecha y la hora ahora se ven de un vistazo —\"Hoy, 14:50\"— y se abren solo si quieres cambiarlas.",
      "Registrar un cobro ya no te pide un \"N° de cuota\": venía con un número puesto que casi nunca era el correcto. Y la pantalla te dice lo que vas a ver después —\"Entra a: Cuenta Principal\", \"Sumar a esa cuenta\"— en vez de hablarte de abonos y de contabilidad.",
      "Subir y bajar lo que alguien te debe eran dos pantallas idénticas. Ahora es una sola, con un botón para elegir: \"Le debe más\" o \"Le debe menos\".",
      "Al ajustar el monto ahora es obligatorio decir por qué —\"Canon M50\", \"préstamo\"—, porque es justo el texto que aparece en el estado de cuenta que le mandas a la otra persona. Antes era opcional, y por eso salían líneas en blanco en el PDF.",
      "Las dos pantallas que abres desde una deuda ya muestran el mismo número: lo que te debe hoy. Antes una decía 21,020 y la otra 23,455 en el mismo sitio, y parecía que una de las dos estaba mal.",
      "Cuando compartes una deuda, con quién la compartiste se lee como un dato más y no como un botón, y \"Desvincular acceso\" bajó al final, separado del resto, para que no se toque por error.",
      "En el plan de pagos a medida ahora se ve de qué mes habla cada cuota —\"Set 2026\", con el año— y de dónde sale la lista: el primer pago arranca en el mes actual y de ahí va uno por mes. Antes salía de la fecha en que abriste la deuda, así que un plan pactado hoy podía empezar con cuatro meses ya vencidos.",
      "Y los meses se pueden cambiar: tocas el mes de un pago y eliges otro. La app solo te ofrece los que no rompen el orden, así que no puedes poner marzo antes de enero.",
      "Elegir el mes de un pago ahora abre su propia pantalla, con el año arriba y los doce meses debajo, en vez de desplegar veinticuatro casillas dentro del formulario que empujaban los totales fuera de vista. Dice de qué pago estás cambiando el mes, los meses que ya tienen un pago aparecen marcados y no se pueden elegir dos veces, y el botón dice lo que va a pasar: \"Usar Nov 2026\".",
      "Y ya no hay un tope de dos años: antes la lista se cortaba en agosto de 2028 sin decir por qué, así que un acuerdo que llegara a 2029 no se podía escribir.",
      "El teclado numérico ya trae un botón \"Listo\" para cerrarlo. En iPhone, los teclados de solo números no tienen tecla de retorno, así que para cerrarlos había que acertar tocando en un sitio concreto del formulario — y por eso a veces parecía que salía con botón y a veces no.",
      "Y si tocas \"seleccionar cuenta\" con el teclado abierto, ahora se cierra solo: antes la lista de cuentas se abría por debajo del teclado y no se veía.",
      "Al escribir un monto dentro de una hoja —el plan de pagos, \"Más detalles\"— el teclado ya no tapa lo que estás escribiendo: la hoja sube. Y los botones del pie dejaron de quedar pegados al borde inferior del teléfono.",
      "Al registrar un cobro o un pago, la app ahora te dice a qué cuota va: \"Cuota 3 de 6 · Nov 2026 · S/ 300.00\". Antes solo veías el saldo entero, así que no había forma de saber cuál estabas cubriendo. Y va por la cuota, no por la fecha: si la de setiembre te la pagan en noviembre, sigue siendo la de setiembre.",
      "Los pagos ahora se aplican en cascada: si te pagan una cuota en dos veces, los dos cobros llenan la misma cuota en vez de ocupar dos. Antes cada cobro se emparejaba con una cuota sin mirar el monto, así que dos pagos del mismo día dejaban dos cuotas marcadas como pagadas a medias.",
      "Y el plan ahora reparte lo que debes hoy, no lo del primer día. Si le prestas más o registras otra venta, el plan se ajusta solo: con cuotas iguales sube el monto de las que faltan, y a medida se alargan las cuotas del final. Lo que ya pagaron se queda al precio que pactaron.",
      "La lista del plan se lee como la de movimientos: una línea por cuota en vez de un bloque, lo ya cubierto plegado en una sola línea, y \"Ver el plan completo\" al pie. Antes salían las doce cuotas seguidas, cada una con la misma explicación repetida debajo.",
      "Al escribir el monto del cobro, la app te dice dónde cae: \"Completa esta cuota y adelanta S/ 50.00 de la siguiente\" o \"Quedarán S/ 20.00 pendientes de esta cuota\".",
      "El detalle de un movimiento entra en una pantalla: eran siete tarjetas para seis datos, y dos de ellas existían solo para decirte que estaban vacías. Ahora es una lista, y cada línea abre justo el campo que quieres corregir.",
      "En ese detalle ves con cuánto quedó la cuenta debajo del monto —\"Cuenta Principal · queda S/ 33.64\"— y la hora a la que registraste el movimiento, que antes había que ir a buscar.",
      "\"Anular\" ya no está pegado a \"Duplicar\" con el mismo tamaño: es la única de las tres que no se deshace con otro toque, así que bajó al final, separada.",
      "El neto de Movimientos ya es el del mes entero desde que abres la pantalla. Antes solo sumaba los movimientos que se habían cargado, así que el número cambiaba mientras bajabas y había un aviso avisándote de que no era el de verdad. Ese aviso ya no hace falta.",
      "Bajar por Movimientos vuelve a ser por tandas. La app se guardaba en el teléfono todos los movimientos que hubieras cargado alguna vez, así que a partir del segundo día ya no paginaba nada: abrías y estaba el mes entero de golpe. Ahora guarda solo la primera tanda y el resto se pide al bajar. Además pide la siguiente cuando de verdad te acercas al final —antes lo hacía faltándote dos pantallas— y las filas dejaron de deslizarse cada vez que asoman: el scroll ya no da tirones.",
      "Los filtros de Movimientos se abren como lista, igual que en Cuentas y en Créditos y deudas. Eran una fila que se desplazaba de lado y en la que cabían dos y media: \"Transferencias\", \"Obligaciones\" y \"Suscripciones\" quedaban fuera de la pantalla y había que empujar a ciegas para encontrarlas.",
      "En Notificaciones ya no se te esconden las viejas. La app solo cargaba las 100 más recientes: si tenías 200, las otras 100 no existían para ella, y el recuento de arriba decía \"100 sin leer\" cuando eran 200 —así que \"Leer todas\" parecía no funcionar. Ahora el recuento lo hace el servidor y siempre es el de verdad, y si alguna vez la lista no las trae todas, te lo dice en vez de callarlo.",
      "El análisis de una cuenta ahora empieza diciéndote lo que pasó, en una frase, en vez de cuatro recuadros que había que interpretar. Y separa lo que de verdad gastaste de lo que solo moviste a otra cuenta tuya: en la Cuenta Sueldo salieron S/ 32,654 pero gastados fueron S/ 10,120 — el resto eran traspasos entre tus propias cuentas.",
      "Se fue la dona de entradas contra salidas: en una cuenta de diario siempre dibuja mitad y mitad, porque lo que entra acaba saliendo, así que no decía nada. También se fue el gasto por día de la semana, que ya está en Patrones y ahí sí con la cifra.",
      "Y \"Sin categoría\" deja de competir como si fuera una categoría más: en esa cuenta era la primera del ranking con S/ 3,382, o sea que lo más grande era no saber en qué se gastó. Ahora baja a su propia línea con un botón que te lleva a arreglarlo.",
      "Ver archivadas está ahora en el mismo sitio en Cuentas y en Créditos y deudas: junto al botón de agrupar, al lado de los filtros. Antes en cada módulo estaba en un lugar distinto.",
      "Créditos y deudas también se pueden agrupar: separados en \"Me deben\" y \"Yo debo\".",
      "Una deuda o crédito que alguien compartió contigo ya se puede quitar de tu lista, deslizándola o manteniéndola pulsada. Antes se quedaba ahí para siempre. La cuenta sigue siendo de la otra persona: lo que se quita es tu acceso, así que para recuperarla tendría que volver a compartírtela.",
      "Archivar y eliminar una cuenta se hace solo desde la lista —deslizando o manteniendo pulsado—, como en el resto de la app. Los botones que había dentro del formulario de la cuenta se fueron, y eliminar (que solo se puede en una cuenta archivada) está ahora al deslizar hacia el otro lado, para que no se toque por error.",
    ],
  },
  {
    version: "1.0.9",
    title: "Detecta tus pagos desde el correo",
    changes: [
      "Ya puedes detectar tus pagos automáticamente desde el correo: en Configuración generas una dirección privada, reenvías ahí los correos que te manda tu banco y DarkMoney te sugiere el movimiento listo para confirmar. Es la forma de detectar pagos en iPhone.",
      "La app abre bastante más rápido y puedes registrar un movimiento de inmediato, sin esperar a que terminen de cargar tus créditos, deudas y presupuestos.",
      "Si tocas \"Guardar\" dos veces por nervios, ya no se registra dos veces.",
      "Cuando la conexión falla —se pone lenta, cambias de WiFi a datos móviles o se corta a mitad de un guardado— la app se recupera sola y no pierdes lo que habías escrito.",
    ],
  },
  {
    version: "1.0.8",
    title: "El asistente te habla",
    changes: [
      "El asistente puede responderte en voz alta: activa el \"modo hablante\", háblale y te contesta hablando. Ideal para consultar tu plata sin mirar la pantalla. (Pro)",
    ],
  },
  {
    version: "1.0.7",
    title: "Tus notificaciones intactas y un asistente más listo",
    changes: [
      "DarkMoney ya nunca borra las notificaciones de otras apps (banco, Yape, correo): solo muestra su aviso al lado.",
      "Los movimientos detectados que quedaban \"guardándose\" ahora se guardan solos al abrir la app.",
      "El asistente compara meses (\"¿gasté más que el mes pasado?\"), calcula ganancias de reventa y puede crear presupuestos, deudas y suscripciones por chat, siempre pidiéndote confirmar antes. (Pro)",
    ],
  },
  {
    version: "1.0.6",
    title: "Habla para registrar",
    changes: [
      "Puedes dictar por voz tus movimientos al asistente en vez de escribir. (Pro)",
      "Mejoras en los recordatorios de presupuestos.",
    ],
  },
  {
    version: "1.0.5",
    title: "Reportes para compartir",
    changes: [
      "Nuevo reporte en PDF de créditos y deudas: un documento claro que puedes mandar por WhatsApp para mostrar cuánto se debe y cuánto se ha pagado.",
    ],
  },
];

export const CHANGELOG_OLDER =
  "Versiones anteriores: mejoras de rendimiento, avisos inteligentes y estabilidad general.";
