import { StyleSheet } from "react-native";

import { COLORS, FONT_FAMILY, FONT_SIZE, RADIUS, SPACING, SURFACE } from "../../../constants/theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },
  content: { padding: SPACING.lg, gap: SPACING.md, paddingBottom: SPACING.xl },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  errorText: { color: COLORS.storm, fontSize: FONT_SIZE.md },
  headerActions: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  shareBtn: {
    paddingHorizontal: SPACING.sm, paddingVertical: 4,
    borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.income + "88",
  },
  headerIconBtn: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.full,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    backgroundColor: SURFACE.card,
  },
  shareBtnText: { fontSize: FONT_SIZE.xs, color: COLORS.income, fontFamily: FONT_FAMILY.bodyMedium },
  unlinkHeaderBtn: {
    borderColor: COLORS.expense + "66",
    backgroundColor: COLORS.expense + "12",
  },
  unlinkHeaderBtnText: {
    color: COLORS.expense,
  },
  detailInfoCard: {
    gap: 0,
  },
  detailInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  // La moneda iba en una cápsula violeta: un color que no está en el sistema —y donde sí está,
  // significa IA— para un dato que es una etiqueta más.
  detailInfoBadge: {
    color: COLORS.storm,
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.body,
  },
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  shareSheet: {
    gap: SPACING.md,
  },
  shareSheetSub: { fontSize: FONT_SIZE.sm, color: COLORS.storm, textAlign: "center", marginTop: -SPACING.sm },
  // La cifra va a la izquierda, como el resto de los números de la app: la tarjeta apilaba
  // cuatro líneas centradas para decir uno solo.
  heroBlock: { alignItems: "flex-start", gap: SPACING.xs, paddingBottom: SPACING.xs },
  // El color estaba inline y venía de la dirección de la deuda —verde o rojo—; sin él el texto
  // se iba a negro sobre la tarjeta oscura. La cifra es hueso, como todas.
  pendingAmount: {
    fontSize: 36,
    fontFamily: FONT_FAMILY.heading,
    color: COLORS.ink,
    letterSpacing: -0.5,
  },
  pendingLabel: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodySemibold,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  progress: { width: "100%", marginTop: SPACING.sm },
  progressLabel: { fontSize: FONT_SIZE.xs, color: COLORS.storm },
  capitalSummaryCard: {
    gap: SPACING.sm,
  },
  heroTerms: {
    marginTop: SPACING.sm,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  capitalMathRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: SPACING.md,
    paddingVertical: SPACING.xs + 2,
  },
  capitalMathLabel: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.fog,
  },
  capitalMathValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  capitalMathTotalRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: SURFACE.separator,
    marginTop: SPACING.xs,
    paddingTop: SPACING.sm,
  },
  capitalMathTotalLabel: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  capitalMathTotalValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  section: { gap: SPACING.sm },
  sectionTitle: {
    fontSize: FONT_SIZE.xs, fontFamily: FONT_FAMILY.bodySemibold,
    color: COLORS.storm, textTransform: "uppercase", letterSpacing: 0.5,
  },
  sectionHint: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textDisabled,
    lineHeight: 18,
  },
  historyHeaderRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  historyScopeLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  customRange: {
    gap: SPACING.sm,
    marginTop: SPACING.xs,
  },
  emptyHistory: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    lineHeight: 20,
  },
  historyGroupCard: {
    gap: SPACING.xs,
  },
  historyGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    paddingHorizontal: 4,
    minHeight: 40,
  },
  historyGroupHeaderLeft: {
    flex: 1,
  },
  historyGroupTitle: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodySemibold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  historyGroupToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.separator,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
  },
  historyGroupBadge: {
    backgroundColor: SURFACE.cardBorder,
    borderRadius: RADIUS.full,
    paddingHorizontal: 7,
    paddingVertical: 1,
  },
  historyGroupBadgeText: {
    fontSize: 10,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  historyGroupBody: {
    gap: 0,
  },
  historyGroupEmpty: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    lineHeight: 18,
    paddingVertical: SPACING.xs,
    paddingHorizontal: 4,
  },
  dateSeparator: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
    paddingTop: 12,
    paddingBottom: 6,
    gap: 8,
  },
  dateSepLine: {
    flex: 1,
    height: 1,
    backgroundColor: SURFACE.separator,
  },
  // La cabecera es del mes, no del día, y va en gris: el neto tiene su signo, que es lo que
  // dice hacia dónde se movió la deuda. En menta decía "entró plata" sobre pagos y descuentos.
  datePillText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodySemibold,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  dateDayTotal: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.heading,
    color: COLORS.fog,
  },
  dateGroup: {},
  viewerTabsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  viewerTabChip: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    backgroundColor: SURFACE.separator,
  },
  viewerTabChipActive: {
    borderColor: COLORS.primary + "66",
    backgroundColor: COLORS.primary + "16",
  },
  viewerTabChipText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  viewerTabChipTextActive: {
    color: COLORS.primary,
  },
  eventFocusNotice: {
    borderRadius: RADIUS.full,
    borderWidth: 1,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs + 2,
    alignSelf: "flex-start",
  },
  eventFocusNoticeInfo: {
    backgroundColor: COLORS.primary + "10",
    borderColor: COLORS.primary + "20",
  },
  eventFocusNoticeSuccess: {
    backgroundColor: COLORS.income + "10",
    borderColor: COLORS.income + "20",
  },
  eventFocusNoticeText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  eventFocusNoticeTextInfo: {
    color: COLORS.primary,
  },
  eventFocusNoticeTextSuccess: {
    color: COLORS.income,
  },
  // Sin caja: cada movimiento era una tarjeta con fondo, borde y esquinas, y la lista quedaba
  // en bloques apilados. Una lista de movimientos son filas separadas por una línea, como en
  // Movimientos y en Cuentas.
  eventCard: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: SURFACE.separator,
  },
  eventCardInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.md,
    gap: SPACING.md,
  },
  eventCardBody: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  // El color venía inline, del tipo de evento. Ahora el título es el producto y el monto lleva
  // su signo, así que los dos van en hueso — y con color propio, que sin él se van a negro.
  eventTypeLabel: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONT_FAMILY.bodyMedium,
    color: COLORS.ink,
    lineHeight: 20,
  },
  eventCardAmount: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONT_FAMILY.heading,
    color: COLORS.ink,
    flexShrink: 0,
  },
  eventAmountColumn: {
    alignItems: "flex-end",
    gap: 2,
  },
  eventBalanceAfter: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  eventImpactNote: {
    fontSize: 10,
    fontFamily: FONT_FAMILY.bodyMedium,
    marginTop: 1,
  },
  eventChipsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: SPACING.xs,
    paddingHorizontal: 14,
    paddingBottom: 10,
    paddingTop: 0,
  },
  eventRowHighlighted: {
    backgroundColor: COLORS.income + "08",
    borderColor: COLORS.income + "28",
  },
  eventRowHighlightedPulse: {
    backgroundColor: COLORS.income + "12",
    borderColor: COLORS.income + "42",
  },
  eventMainPress: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  eventAccent: {
    width: 4,
    alignSelf: "stretch",
    minHeight: 48,
    borderRadius: RADIUS.full,
  },
  eventBody: {
    flex: 1,
    gap: SPACING.xs,
    minWidth: 0,
  },
  eventHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  eventInfo: { gap: 2, flex: 1, minWidth: 0 },
  eventRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: SPACING.xs,
    flexWrap: "wrap",
    flexShrink: 1,
    maxWidth: "55%",
  },
  eventType: { fontSize: FONT_SIZE.sm, fontFamily: FONT_FAMILY.bodyMedium, color: COLORS.ink },
  eventDate: { fontSize: FONT_SIZE.xs, color: COLORS.storm },
  eventDescription: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    lineHeight: 16,
  },
  eventDescriptionMuted: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textDisabled,
    fontFamily: FONT_FAMILY.body,
    fontStyle: "italic",
    lineHeight: 16,
  },
  eventNotes: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  eventAmountGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    flexShrink: 0,
  },
  eventAmountPill: {
    borderRadius: RADIUS.full,
    borderWidth: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    maxWidth: 150,
  },
  eventAmount: { fontSize: FONT_SIZE.sm, fontFamily: FONT_FAMILY.bodySemibold },
  eventChevron: { fontSize: FONT_SIZE.md, color: COLORS.storm, marginTop: 1 },
  eventInlineMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginTop: 2,
  },
  eventMetaChip: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(244,241,236,0.05)",
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.10)",
  },
  eventMetaChipText: {
    fontSize: 10,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  eventMetaChipCash: {
    backgroundColor: COLORS.primary + "14",
    borderColor: COLORS.primary + "32",
  },
  eventMetaChipTextCash: {
    color: COLORS.primary,
  },
  eventMetaChipCapital: {
    backgroundColor: COLORS.secondary + "14",
    borderColor: COLORS.secondary + "32",
  },
  eventMetaChipTextCapital: {
    color: COLORS.secondary,
  },
  eventMetaChipPositive: {
    backgroundColor: COLORS.income + "14",
    borderColor: COLORS.income + "32",
  },
  eventMetaChipTextPositive: {
    color: COLORS.income,
  },
  eventMetaChipNegative: {
    backgroundColor: COLORS.danger + "14",
    borderColor: COLORS.danger + "32",
  },
  eventMetaChipTextNegative: {
    color: COLORS.danger,
  },
  eventMetaChipNeutral: {
    backgroundColor: "rgba(244,241,236,0.05)",
    borderColor: "rgba(244,241,236,0.10)",
  },
  eventMetaChipTextNeutral: {
    color: COLORS.storm,
  },
  eventAccountImpactNote: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    lineHeight: 17,
  },
  eventAttachmentRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: SPACING.xs,
    paddingLeft: SPACING.md,
    marginTop: 4,
  },
  eventAttachmentChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "14",
    borderWidth: 1,
    borderColor: COLORS.primary + "38",
  },
  eventAttachmentChipText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  eventAttachmentLoadingChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(244,241,236,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.08)",
  },
  eventAttachmentLoadingText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
  ownerEventDeletePendingChip: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.danger + "16",
    borderWidth: 1,
    borderColor: COLORS.danger + "36",
  },
  ownerEventDeletePendingText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.danger,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  eventMenuSheet: {
    paddingTop: SPACING.xs,
    gap: SPACING.sm,
  },
  eventMenuHandle: {
    width: 36, height: 4, borderRadius: 2,
    backgroundColor: COLORS.border, alignSelf: "center", marginBottom: SPACING.xs,
  },
  eventMenuTitle: { fontSize: FONT_SIZE.md, fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.ink, textAlign: "center" },
  eventMenuSub: { fontSize: FONT_SIZE.sm, color: COLORS.storm, textAlign: "center", marginBottom: SPACING.xs },
  eventMenuBtn: { marginTop: SPACING.xs },
  eventMenuStatusNote: { fontSize: FONT_SIZE.xs, color: COLORS.danger, textAlign: "center" },
  eventMenuDeleteBtn: { borderColor: COLORS.expense + "66" },
  // Los dos botones comparten alto y línea base: el primario arrastraba un marginTop de cuando
  // vivía solo, y su alto salía del padding mientras el otro lo fijaba, así que ninguno de los
  // dos empezaba donde el otro.
  payBtn: {
    flex: 1,
    minHeight: 48,
    backgroundColor: COLORS.ink,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  payRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  paySecondaryBtn: {
    minHeight: 48,
    paddingHorizontal: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    backgroundColor: SURFACE.card,
  },
  paySecondaryBtnText: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.sm,
    color: COLORS.fog,
  },
  // Sobre hueso el texto va en el fondo de la app, como en el botón principal del resto de las
  // pantallas. Era blanco sobre menta: el color que significa plata que entra, en un botón.
  payBtnText: { color: COLORS.bgVoid, fontSize: FONT_SIZE.md, fontFamily: FONT_FAMILY.bodySemibold },
  requestBadgeWrap: { position: "relative" },
  requestBadge: {
    backgroundColor: COLORS.danger,
    borderRadius: RADIUS.full,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  requestBadgeText: { color: "#FFF", fontSize: 11, fontFamily: FONT_FAMILY.bodySemibold },
  requestGroupTitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
    marginTop: SPACING.xs,
  },
  requestCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    backgroundColor: "rgba(244,241,236,0.04)",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.danger + "33",
    padding: SPACING.sm,
  },
  requestInfo: { flex: 1, gap: 2 },
  requestName: { fontSize: FONT_SIZE.sm, color: COLORS.storm, fontFamily: FONT_FAMILY.bodyMedium },
  requestAmount: { fontSize: FONT_SIZE.md, color: COLORS.ink, fontFamily: FONT_FAMILY.bodySemibold },
  requestDate: { fontSize: FONT_SIZE.xs, color: COLORS.storm },
  requestDesc: { fontSize: FONT_SIZE.xs, color: COLORS.textDisabled },
  requestAccountChip: {
    marginTop: 2,
    backgroundColor: COLORS.income + "18",
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 2,
    alignSelf: "flex-start",
  },
  requestAccountChipText: { fontSize: 10, color: COLORS.income, fontFamily: FONT_FAMILY.bodyMedium },
  requestNoAccount: { fontSize: 10, color: COLORS.textDisabled, marginTop: 2 },
  requestActions: { flexDirection: "row", alignItems: "center", gap: SPACING.xs, paddingTop: 2 },
  acceptBtn: {
    width: 36, height: 36, alignItems: "center", justifyContent: "center",
    borderRadius: RADIUS.md, backgroundColor: COLORS.income + "18",
  },
  rejectBtn: {
    width: 36, height: 36, alignItems: "center", justifyContent: "center",
    borderRadius: RADIUS.md, backgroundColor: COLORS.danger + "18",
  },
  ownerDeleteRequestCard: {
    gap: SPACING.sm,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.danger + "28",
    backgroundColor: "rgba(14,13,12,0.58)",
    padding: SPACING.md,
  },
  ownerDeleteRequestHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  ownerDeleteRequestTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  ownerDeleteRequestEyebrow: {
    fontSize: 10,
    color: COLORS.danger,
    fontFamily: FONT_FAMILY.bodySemibold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  ownerDeleteRequestTitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  ownerDeleteRequestStatus: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.warning + "16",
    borderWidth: 1,
    borderColor: COLORS.warning + "36",
  },
  ownerDeleteRequestStatusText: {
    fontSize: 10,
    color: COLORS.warning,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  ownerDeleteTargetCard: {
    flexDirection: "row",
    gap: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.10)",
    backgroundColor: "rgba(244,241,236,0.04)",
    padding: SPACING.sm,
  },
  ownerDeleteTargetAccent: {
    width: 3,
    alignSelf: "stretch",
    minHeight: 46,
    borderRadius: RADIUS.full,
  },
  ownerDeleteTargetBody: {
    flex: 1,
    minWidth: 0,
    gap: SPACING.xs,
  },
  ownerDeleteTargetTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  ownerDeleteTargetInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  ownerDeleteTargetType: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  ownerDeleteTargetDate: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  ownerDeleteTargetAmount: {
    maxWidth: 140,
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.bodySemibold,
    textAlign: "right",
  },
  ownerDeleteTargetDesc: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    lineHeight: 17,
  },
  ownerDeleteTargetDescMuted: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textDisabled,
    lineHeight: 17,
  },
  ownerDeleteRequestActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  ownerDeleteFocusBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.secondary + "32",
    backgroundColor: COLORS.secondary + "10",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.sm,
  },
  ownerDeleteFocusText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  ownerDeleteDecisionActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  rejectSheet: {
    backgroundColor: COLORS.mist,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  rejectTitle: { fontSize: FONT_SIZE.md, fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.ink, textAlign: "center" },
  rejectSub: { fontSize: FONT_SIZE.sm, color: COLORS.storm, textAlign: "center" },
  rejectInputWrap: {
    backgroundColor: "rgba(244,241,236,0.05)",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.1)",
    padding: SPACING.sm,
  },
  rejectInput: { color: COLORS.ink, fontSize: FONT_SIZE.md, fontFamily: FONT_FAMILY.body },
  rejectConfirmBtn: { borderColor: COLORS.danger + "66" },
  ownerEditSummaryCard: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary + "33",
    backgroundColor: COLORS.primary + "10",
    padding: SPACING.sm,
    gap: SPACING.xs,
  },
  ownerEditSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  ownerEditSummaryLabel: {
    flex: 1,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
  ownerEditSummaryValue: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  ownerEditSummaryStrong: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.primary,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  viewerAccountLinkedChip: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.income + "14",
    borderWidth: 1,
    borderColor: COLORS.income + "30",
  },
  viewerAccountLinkedText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.income,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  viewerAccountLinkedChipNegative: {
    backgroundColor: COLORS.danger + "14",
    borderColor: COLORS.danger + "30",
  },
  viewerAccountLinkedTextNegative: {
    color: COLORS.danger,
  },
  viewerAccountUnlinkedChip: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(244,241,236,0.05)",
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.10)",
  },
  viewerAccountUnlinkedText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  viewerEventActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    flexWrap: "wrap",
    paddingLeft: SPACING.md,
  },
  viewerEditPendingChip: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.warning + "20",
    borderWidth: 1,
    borderColor: COLORS.warning + "44",
  },
  viewerEditPendingText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.warning,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  viewerEventManageHint: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textDisabled,
    fontFamily: FONT_FAMILY.bodyMedium,
    fontStyle: "italic",
  },
  viewerDeletePendingChip: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.warning + "20",
    borderWidth: 1,
    borderColor: COLORS.warning + "44",
  },
  viewerDeletePendingText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.warning,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  viewerDeleteAcceptedChip: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.income + "20",
    borderWidth: 1,
    borderColor: COLORS.income + "44",
  },
  viewerDeleteAcceptedText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.income,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  linkSheet: {
    backgroundColor: COLORS.mist,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  linkSheetTitle: { fontSize: FONT_SIZE.md, fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.ink, textAlign: "center" },
  linkSheetSub: { fontSize: FONT_SIZE.sm, color: COLORS.storm, textAlign: "center", marginTop: -SPACING.xs },
  linkSheetHint: { fontSize: FONT_SIZE.xs, color: COLORS.textDisabled, textAlign: "center" },
  linkSheetImpactCard: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    padding: SPACING.sm,
    gap: 4,
  },
  linkSheetImpactCardPositive: {
    backgroundColor: COLORS.income + "10",
    borderColor: COLORS.income + "26",
  },
  linkSheetImpactCardNegative: {
    backgroundColor: COLORS.danger + "10",
    borderColor: COLORS.danger + "26",
  },
  linkSheetImpactCardNeutral: {
    backgroundColor: "rgba(244,241,236,0.04)",
    borderColor: "rgba(244,241,236,0.10)",
  },
  linkSheetImpactTitle: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  linkSheetImpactTitlePositive: {
    color: COLORS.income,
  },
  linkSheetImpactTitleNegative: {
    color: COLORS.danger,
  },
  linkSheetImpactTitleNeutral: {
    color: COLORS.ink,
  },
  linkSheetImpactBody: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    lineHeight: 17,
  },
  ownerAccountLabel: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  linkAccountRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(244,241,236,0.08)",
    backgroundColor: "rgba(244,241,236,0.04)",
  },
  linkAccountRowSelected: {
    borderColor: COLORS.primary + "88",
    backgroundColor: COLORS.primary + "18",
  },
  linkAccountInfo: { flex: 1, gap: 2 },
  linkAccountName: { fontSize: FONT_SIZE.sm, color: COLORS.ink, fontFamily: FONT_FAMILY.bodyMedium },
  linkAccountBalance: { fontSize: FONT_SIZE.xs, color: COLORS.storm },
  linkAccountCheck: { fontSize: FONT_SIZE.md, color: COLORS.primary, fontFamily: FONT_FAMILY.bodySemibold },
  accountProjectionCard: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary + "33",
    backgroundColor: COLORS.primary + "12",
    padding: SPACING.sm,
    gap: 6,
  },
  accountProjectionTitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  accountProjectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  accountProjectionLabel: {
    flex: 1,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
  accountProjectionValue: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  accountProjectionStrong: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  accountProjectionPositive: {
    color: COLORS.income,
  },
  accountProjectionNegative: {
    color: COLORS.danger,
  },
  linkNoAccounts: { fontSize: FONT_SIZE.sm, color: COLORS.storm, textAlign: "center", paddingVertical: SPACING.sm },
  viewerRequestCard: {
    backgroundColor: "rgba(244,241,236,0.04)",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    padding: SPACING.sm,
    gap: 4,
  },
  viewerRequestHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  viewerRequestAmount: { fontSize: FONT_SIZE.md, color: COLORS.ink, fontFamily: FONT_FAMILY.bodySemibold },
  viewerRequestStatus: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 2,
    borderRadius: RADIUS.full,
  },
  viewerRequestStatusText: { fontSize: FONT_SIZE.xs, fontFamily: FONT_FAMILY.bodyMedium },
  viewerRequestDate: { fontSize: FONT_SIZE.xs, color: COLORS.storm },
  viewerRequestDesc: { fontSize: FONT_SIZE.xs, color: COLORS.textDisabled },
  viewerRequestNote: { fontSize: FONT_SIZE.xs, color: COLORS.textDisabled, marginTop: 2 },
  viewerEmptyState: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    backgroundColor: SURFACE.card,
    padding: SPACING.md,
  },
  viewerEmptyStateText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
});
