import { StyleSheet } from "react-native";

import { COLORS, ELEVATION, FONT_FAMILY, FONT_SIZE, RADIUS, SPACING, SURFACE } from "../../constants/theme";

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  approvalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    padding: SPACING.lg,
  },
  sheet: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
  },
  approvalSheet: {
    backgroundColor: "rgba(8,12,18,0.98)",
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  approvalTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
    textAlign: "center",
  },
  approvalSub: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    textAlign: "center",
  },
  approvalLabel: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
  },
  approvalAccountRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  approvalAccountRowSelected: {
    borderColor: COLORS.primary + "88",
    backgroundColor: COLORS.primary + "18",
  },
  approvalAccountInfo: {
    flex: 1,
    gap: 2,
  },
  approvalAccountName: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  approvalAccountBalance: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  approvalProjectionCard: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary + "33",
    backgroundColor: COLORS.primary + "12",
    padding: SPACING.sm,
    gap: 6,
  },
  approvalProjectionTitle: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  approvalProjectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  approvalProjectionLabel: {
    flex: 1,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
  approvalProjectionValue: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  approvalProjectionStrong: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  approvalProjectionPositive: {
    color: COLORS.income,
  },
  approvalProjectionNegative: {
    color: COLORS.danger,
  },
  approvalAccountCheck: {
    fontSize: FONT_SIZE.md,
    color: COLORS.primary,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  approvalActions: {
    marginTop: SPACING.xs,
    gap: SPACING.sm,
  },
  approvalAcceptBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.income + "18",
    borderWidth: 1,
    borderColor: COLORS.income + "44",
  },
  approvalAcceptText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.income,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  approvalCancelText: {
    textAlign: "center",
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },
  viewerDangerBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.danger + "18",
    borderWidth: 1,
    borderColor: COLORS.danger + "44",
  },
  viewerDangerBtnText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.danger,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  viewerStatusChipPending: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.warning + "18",
    borderWidth: 1,
    borderColor: COLORS.warning + "44",
  },
  viewerStatusChipPendingText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.warning,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  viewerStatusChipAccepted: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.income + "18",
    borderWidth: 1,
    borderColor: COLORS.income + "44",
  },
  viewerStatusChipAcceptedText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.income,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  viewerActionNote: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textAlign: "center",
    fontFamily: FONT_FAMILY.body,
  },
  viewerDisabledBtn: {
    opacity: 0.45,
  },
  card: {
    maxHeight: "92%",
    backgroundColor: SURFACE.sheet,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopColor: SURFACE.separator,
    borderLeftColor: SURFACE.separator,
    borderRightColor: SURFACE.separator,
    ...ELEVATION[4],
  },
  handle: {
    alignSelf: "center",
    width: 36,
    height: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.22)",
    marginTop: SPACING.md,
    marginBottom: SPACING.xs,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 0.5,
    borderBottomColor: "rgba(255,255,255,0.10)",
  },
  headerText: { flex: 1 },
  title: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.lg,
    color: COLORS.ink,
  },
  subtitle: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    marginTop: 2,
  },
  closeBtn: {
    padding: SPACING.xs,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: RADIUS.sm,
  },
  content: {
    padding: SPACING.lg,
    gap: SPACING.lg,
    paddingBottom: SPACING.xxxl,
  },

  // ── Progress ──
  progressSection: { gap: SPACING.xs },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  progressPct: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  dueDate: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  progressHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  progressAmounts: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  amountSmall: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },

  // ── Metrics ──
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  insightGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  metricCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    padding: SPACING.md,
    gap: 4,
    alignItems: "flex-start",
  },
  metricValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
  },
  metricLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  metricsFootnote: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
    marginTop: -SPACING.xs,
  },
  insightCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: SPACING.md,
    gap: 4,
  },
  insightValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  insightLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
  },
  insightSub: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  insightPositive: {
    color: COLORS.income,
  },
  insightWarning: {
    color: COLORS.warning,
  },
  insightNegative: {
    color: COLORS.danger,
  },

  // ── Section ──
  section: { gap: SPACING.sm },
  sectionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  comparisonNarrativeCard: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    padding: SPACING.md,
    gap: 6,
  },
  comparisonNarrativeEyebrow: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  comparisonNarrativeLead: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  comparisonNarrativeBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 20,
  },
  comparisonNarrativeFootnote: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  sectionHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  dateRangeCaption: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textDisabled,
    lineHeight: 18,
  },
  historyPresetRow: {
    flexDirection: "row",
    gap: SPACING.xs,
    paddingVertical: SPACING.xs,
  },
  pillRowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginTop: SPACING.sm,
  },
  filterPill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.card,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
  },
  filterPillActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  filterPillText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodyMedium,
    color: COLORS.storm,
  },
  filterPillTextActive: {
    color: "#FFFFFF",
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  customRange: { gap: SPACING.sm, marginTop: SPACING.xs },

  // ── Chart ──
  chartScroll: {
    flexGrow: 1,
    paddingVertical: SPACING.xs,
  },
  chart: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: SPACING.xs,
    height: 88,
    minWidth: "100%",
  },
  chartWide: {
    minWidth: undefined,
    paddingRight: SPACING.md,
  },
  chartBar: {
    flex: 1,
    minWidth: 28,
    alignItems: "center",
    gap: 3,
  },
  chartBarFixed: {
    flex: 0,
    width: 40,
  },
  barTrack: {
    flex: 1,
    width: "100%",
    justifyContent: "flex-end",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 4,
    overflow: "hidden",
  },
  barFill: {
    width: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 4,
    minHeight: 3,
  },
  barFillPositive: {
    backgroundColor: COLORS.income,
  },
  barFillNegative: {
    backgroundColor: COLORS.danger,
  },
  barEmpty: { backgroundColor: "transparent", minHeight: 0 },
  barLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 10,
    color: COLORS.storm,
    textTransform: "capitalize",
  },
  barValue: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: 9,
    color: COLORS.primary,
  },

  // ── Installment grid ──
  installmentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  installmentCell: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  installmentPaid: {
    backgroundColor: COLORS.pine + "22",
    borderColor: COLORS.pine + "55",
  },
  installmentPending: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  installmentNum: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: 11,
  },

  // ── Event history ──
  historyPager: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: SPACING.md,
    paddingTop: SPACING.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.12)",
    gap: SPACING.sm,
  },
  historyPagerBtn: {
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  historyPagerBtnDisabled: {
    opacity: 0.35,
  },
  historyPagerText: {
    flex: 1,
    textAlign: "center",
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodyMedium,
    color: COLORS.storm,
  },
  emptyHistory: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    textAlign: "center",
    paddingVertical: SPACING.md,
  },
  eventRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  eventDot: {
    width: 20,
    height: 20,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    flexShrink: 0,
  },
  eventDotInner: {
    width: 7,
    height: 7,
    borderRadius: RADIUS.full,
  },
  eventInfo: { flex: 1, gap: 2 },
  eventTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    flexWrap: "wrap",
  },
  eventLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  installmentBadge: {
    backgroundColor: COLORS.primary + "22",
    borderRadius: RADIUS.full,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  installmentBadgeText: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: 10,
    color: COLORS.primary,
  },
  eventAmount: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.sm,
    marginLeft: "auto" as any,
  },
  eventDesc: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
  },
  eventReason: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontStyle: "italic",
  },
  eventDate: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    marginTop: 1,
  },
  historyTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  pendingCountBadge: {
    backgroundColor: COLORS.warning + "22",
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: COLORS.warning + "44",
  },
  pendingCountBadgeText: {
    fontSize: 10,
    color: COLORS.warning,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  filterPillPending: {
    borderColor: COLORS.warning + "66",
  },
  requestRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderLeftWidth: 2,
    paddingLeft: SPACING.xs,
    marginLeft: -SPACING.xs,
  },
  requestActions: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginTop: SPACING.xs,
  },
  acceptInlineBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.income + "18",
    borderWidth: 1,
    borderColor: COLORS.income + "44",
  },
  rejectInlineBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.danger + "18",
    borderWidth: 1,
    borderColor: COLORS.danger + "44",
  },
  requestActionText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  rejectInline: {
    marginTop: SPACING.xs,
    gap: SPACING.xs,
  },
  rejectInlineInput: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    padding: SPACING.xs + 2,
    color: COLORS.ink,
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.body,
  },
  rejectInlineActions: {
    flexDirection: "row",
    gap: SPACING.sm,
    alignItems: "center",
  },
  rejectInlineConfirm: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.danger + "22",
    borderWidth: 1,
    borderColor: COLORS.danger + "55",
  },
  rejectInlineConfirmText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.danger,
    fontFamily: FONT_FAMILY.bodyMedium,
  },
  rejectInlineCancelText: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
  },

  // Spark card
  sparkCard: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    padding: SPACING.md,
    gap: SPACING.sm,
  },
  sparkHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sparkAvg: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.lg,
    color: COLORS.ink,
  },
  sparkAvgLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    marginTop: 2,
  },
  sparkMonths: {
    flexDirection: "row",
    gap: 2,
  },
  sparkMonthItem: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  sparkMonthLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 9,
    color: COLORS.storm,
    textTransform: "capitalize",
  },
  sparkMonthVal: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: 9,
    color: COLORS.primary,
  },
  sparkMonthZero: {
    color: COLORS.storm,
  },
  timelinePerspectiveHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
    marginTop: -SPACING.xs,
  },
  timelineSummaryCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  timelineSummaryPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 10,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  timelineSummaryPositivePill: {
    borderColor: COLORS.income + "44",
    backgroundColor: COLORS.income + "14",
  },
  timelineSummaryNegativePill: {
    borderColor: COLORS.expense + "44",
    backgroundColor: COLORS.expense + "14",
  },
  timelineSummaryNeutralPill: {
    borderColor: "rgba(255,255,255,0.12)",
  },
  timelineSummaryValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  timelineSummaryPositiveValue: {
    color: COLORS.income,
  },
  timelineSummaryNegativeValue: {
    color: COLORS.expense,
  },
  timelineSummaryLabel: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  timelineCard: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    padding: SPACING.md,
    gap: SPACING.sm,
  },
  timelineRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    alignItems: "flex-start",
  },
  timelineRowBorder: {
    marginBottom: SPACING.xs,
  },
  timelineRail: {
    width: 24,
    alignItems: "center",
    position: "relative",
    minHeight: 88,
  },
  timelineLine: {
    position: "absolute",
    top: 18,
    bottom: -SPACING.md,
    width: 2,
    borderRadius: RADIUS.full,
  },
  timelineDot: {
    width: 18,
    height: 18,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  timelineDotInner: {
    width: 7,
    height: 7,
    borderRadius: RADIUS.full,
  },
  timelineContent: {
    flex: 1,
    minWidth: 0,
  },
  timelineSurface: {
    gap: SPACING.xs,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  timelineTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  timelineMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  timelineDatePill: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  timelineImpactPill: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    borderWidth: 1,
  },
  timelineImpactText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: 10,
  },
  timelineType: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
  },
  timelineAmount: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.sm,
    flexShrink: 0,
  },
  timelineDate: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: 10,
    color: COLORS.storm,
  },
  timelineDescription: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    lineHeight: 18,
  },

  // ── ESTILO 2 Timeline ──────────────────────────────────────────────────────
  tl2Container: {
    paddingHorizontal: 4,
    marginTop: SPACING.xs,
  },
  tl2DateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 14,
    marginBottom: 6,
    gap: 0,
  },
  tl2NodeCol: {
    width: 28,
    alignItems: "center",
  },
  tl2DateDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.storm,
    borderWidth: 2,
    borderColor: "rgba(18,20,26,1)",
  },
  tl2DateLabel: {
    fontSize: 10,
    fontFamily: FONT_FAMILY.bodySemibold,
    color: COLORS.storm,
    letterSpacing: 0.8,
    marginLeft: 6,
  },
  tl2DateLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.07)",
    marginLeft: 10,
  },
  tl2DayTotal: {
    fontSize: 10,
    fontFamily: FONT_FAMILY.bodySemibold,
    marginLeft: 8,
  },
  tl2EventRow: {
    flexDirection: "row",
  },
  tl2LineCol: {
    width: 28,
    alignItems: "center",
  },
  tl2LineSegment: {
    width: 2,
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.07)",
    minHeight: 8,
  },
  tl2LineEnd: {
    flex: 1,
    minHeight: 6,
  },
  tl2Dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  tl2Card: {
    flex: 1,
    marginLeft: 8,
    marginBottom: 6,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    padding: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  tl2CardBody: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  tl2TypeLabel: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONT_FAMILY.bodySemibold,
    lineHeight: 15,
  },
  tl2CardSubRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 1,
  },
  tl2Badge: {
    borderRadius: 99,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tl2BadgeText: {
    fontSize: 10,
    fontFamily: FONT_FAMILY.bodySemibold,
  },
  tl2CardDesc: {
    fontSize: 10,
    color: COLORS.storm,
    fontFamily: FONT_FAMILY.body,
    flex: 1,
  },
  tl2Amount: {
    fontSize: 13,
    fontFamily: FONT_FAMILY.bodySemibold,
    flexShrink: 0,
  },
});
