import { StyleSheet } from "react-native";

import {
  COLORS,
  ELEVATION,
  EXTENDED_PALETTE,
  FONT_FAMILY,
  FONT_SIZE,
  RADIUS,
  SPACING,
  SURFACE,
} from "../../../../constants/theme";

export const dashboardSimpleStyles = StyleSheet.create({
  sectionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: SPACING.sm,
  },
  macroCard: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    padding: SPACING.md,
    gap: SPACING.md,
  },
  macroHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  macroEyebrow: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  macroTitle: {
    marginTop: 2,
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  macroBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.secondary + "18",
    borderWidth: 1,
    borderColor: COLORS.secondary + "3D",
  },
  macroBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.secondary,
  },
  macroGrid: {
    flexDirection: "row",
    alignItems: "center",
  },
  macroMetric: {
    flex: 1,
    gap: 2,
  },
  macroMetricLabel: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  macroMetricValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.xl,
    color: COLORS.ink,
  },
  macroDivider: {
    width: 1,
    height: 40,
    backgroundColor: SURFACE.separator,
    marginHorizontal: SPACING.md,
  },
  macroHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },

  // Mode toggle
  toggleRow: {
    flexDirection: "row",
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.md,
    padding: 3,
    gap: 3,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[2],
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: SPACING.xs + 2,
    borderRadius: RADIUS.sm,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  toggleBtnActive: {
    backgroundColor: SURFACE.cardActive,
    borderWidth: 0.5,
    borderColor: COLORS.successMuted,
  },
  toggleText: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.storm },
  toggleTextActive: { fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.ink },
  proBadge: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs - 1, color: COLORS.gold },

  // Hero card - most prominent, gets the full premium glass treatment
  heroCard: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    gap: SPACING.xs,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[3],
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  heroPeriodRow: {
    flexDirection: "row",
    gap: 3,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderRadius: RADIUS.full,
    padding: 3,
    alignSelf: "flex-start",
  },
  heroPeriodBtn: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: "transparent",
  },
  heroPeriodBtnActive: {
    backgroundColor: COLORS.pine,
  },
  heroPeriodText: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  heroPeriodTextActive: { fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.textInverse },
  heroCurrencyRow: {
    flexDirection: "row",
    gap: 3,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderRadius: RADIUS.full,
    padding: 3,
  },
  heroCurrencyBtn: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: "transparent",
  },
  heroCurrencyBtnActive: {
    backgroundColor: COLORS.ember,
  },
  heroCurrencyText: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  heroCurrencyTextActive: { fontFamily: FONT_FAMILY.bodySemibold, color: COLORS.textInverse },
  heroLabel: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    letterSpacing: 0.3,
  },
  heroValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 38,
    color: COLORS.ink,
    letterSpacing: -0.5,
    marginTop: 2,
  },
  heroNetPill: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    marginTop: SPACING.xs,
  },
  heroNetText: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },
  heroFlow: {
    flexDirection: "row",
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: 0.5,
    borderTopColor: SURFACE.separator,
  },
  heroFlowItem: { flex: 1, gap: 4 },
  heroFlowIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  heroFlowDot: { width: 8, height: 8, borderRadius: 4 },
  heroFlowLabel: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  heroFlowAmt: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.md },
  heroSep: { width: 0.5, height: 44, backgroundColor: SURFACE.separator, marginHorizontal: SPACING.lg },

  // KPI row
  kpiRow: { flexDirection: "row", gap: SPACING.sm },
  kpiCard: {
    flex: 1,
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    gap: 3,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[2],
  },
  kpiAccent: {
    ...StyleSheet.absoluteFillObject,
  },
  kpiLabel: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: 10, color: COLORS.storm, letterSpacing: 0.2 },
  kpiValue: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.sm },
  kpiChange: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: 9 },
  kpiChangePlaceholder: { fontFamily: FONT_FAMILY.body, fontSize: 9 },

  // Chart
  chartRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
    marginTop: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  chartCol: { flex: 1, alignItems: "center", gap: 4 },
  chartBars: { flexDirection: "row", alignItems: "flex-end", gap: 1, width: "100%" },
  chartBar: { flex: 1, borderTopLeftRadius: 3, borderTopRightRadius: 3, minHeight: 0 },
  chartLabel: { fontFamily: FONT_FAMILY.body, fontSize: 9, color: COLORS.storm, textAlign: "center" },
  chronoHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  chronoTotal: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
  },
  chronoHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
    marginBottom: SPACING.xs,
  },
  chartLegend: { flexDirection: "row", gap: SPACING.lg, marginTop: SPACING.xs },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },

  // Accounts
  accountsRow: { flexDirection: "row", gap: SPACING.sm, paddingVertical: SPACING.xs },
  accountChip: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    alignItems: "center",
    gap: SPACING.xs,
    minWidth: 100,
    maxWidth: 130,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[2],
  },
  accountChipIcon: {
    width: 30,
    height: 30,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  accountChipName: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, textAlign: "center" },
  accountChipBalance: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.sm, color: COLORS.ink, textAlign: "center" },

  // Upcoming
  upcomingKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  upcomingIntro: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  upcomingSummaryRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
  },
  upcomingSummaryCard: {
    flex: 1,
    minHeight: 70,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    gap: 6,
    justifyContent: "space-between",
  },
  upcomingSummaryLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "uppercase",
  },
  upcomingSummaryValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 22,
  },
  upcomingList: {
    gap: SPACING.md,
  },
  upcomingRow: {
    gap: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: SURFACE.track,
  },
  upcomingRowTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.lg,
  },
  upcomingLeft: { flex: 1, minWidth: 0, gap: SPACING.sm },
  upcomingBadge: {
    alignSelf: "flex-start",
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderWidth: 1,
  },
  upcomingBadgeIncome: {
    backgroundColor: "rgba(41, 204, 126, 0.11)",
    borderColor: "rgba(41, 204, 126, 0.28)",
  },
  upcomingBadgeSubscription: {
    backgroundColor: "rgba(111, 120, 255, 0.11)",
    borderColor: "rgba(111, 120, 255, 0.24)",
  },
  upcomingBadgeObligation: {
    backgroundColor: "rgba(255, 95, 95, 0.10)",
    borderColor: "rgba(255, 95, 95, 0.25)",
  },
  upcomingBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: 11,
  },
  upcomingBadgeTextIncome: { color: COLORS.income },
  upcomingBadgeTextSubscription: { color: COLORS.secondary },
  upcomingBadgeTextObligation: { color: COLORS.expense },
  upcomingLabel: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 20,
  },
  upcomingMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: SPACING.sm,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  upcomingDate: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  upcomingAmountPill: {
    flexShrink: 0,
    maxWidth: 136,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 8,
    borderWidth: 1,
  },
  upcomingAmountPillIncome: {
    backgroundColor: "rgba(41, 204, 126, 0.10)",
    borderColor: "rgba(41, 204, 126, 0.24)",
  },
  upcomingAmountPillOut: {
    backgroundColor: "rgba(255, 95, 95, 0.09)",
    borderColor: "rgba(255, 95, 95, 0.22)",
  },
  upcomingAmount: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    textAlign: "right",
  },
  upcomingAmountIncome: { color: COLORS.income },
  upcomingAmountOut: { color: COLORS.rosewood },

  // Budgets
  budgetRow: {
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    gap: SPACING.xs,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[2],
  },
  budgetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  budgetName: { flex: 1, fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  budgetPct: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.sm },
  budgetMeta: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },

  // Leaders (receivable/payable top 3)
  leadersRowContainer: { flexDirection: "row", gap: SPACING.sm },
  leadersCard: {
    flex: 1,
    backgroundColor: SURFACE.card,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    gap: SPACING.xs,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    ...ELEVATION[2],
  },
  leadersTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: SPACING.xs,
  },
  leadersRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: SPACING.xs },
  leadersSep: { borderBottomWidth: 0.5, borderBottomColor: SURFACE.separator },
  leadersName: { flex: 1, fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.ink, paddingRight: 4 },
  leadersAmt: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },

  // Obligations advanced
  obGroupTitle: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs, letterSpacing: 0.2, marginBottom: SPACING.xs },
  obRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.sm,
    borderBottomWidth: 0.5,
    borderBottomColor: SURFACE.separator,
    gap: SPACING.sm,
  },
  obLeft: { flex: 1, gap: 2 },
  obTitle: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  obCounterparty: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  obAmount: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.md },

  // Category breakdown
  catRow: { gap: SPACING.xs, marginBottom: SPACING.sm },
  catLabelRow: { flexDirection: "row", justifyContent: "space-between" },
  catName: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink, flex: 1 },
  catAmount: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.sm, color: COLORS.rosewood },
  catTrack: { height: 6, backgroundColor: SURFACE.track, borderRadius: RADIUS.full, overflow: "hidden" },
  catFill: { height: 6, backgroundColor: COLORS.rosewood + "88", borderRadius: RADIUS.full },

  // Category comparison
  catCompLegend: { flexDirection: "row", gap: SPACING.lg, marginBottom: SPACING.sm },
  catCompRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm, marginBottom: SPACING.sm },
  catCompName: { width: 80, fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.ink },
  catCompBars: { flex: 1, gap: 3 },
  catCompBarTrack: { height: 6, backgroundColor: SURFACE.track, borderRadius: RADIUS.full, overflow: "hidden" },
  catCompBarFill: { height: 6, borderRadius: RADIUS.full },
  catCompAmt: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: 10, color: COLORS.rosewood, width: 60, textAlign: "right" },

  // Subscriptions summary
  subHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: SPACING.sm },
  subTotal: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.md, color: COLORS.rosewood },
  subRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: SPACING.xs + 2,
    borderBottomWidth: 0.5,
    borderBottomColor: SURFACE.separator,
  },
  subName: { flex: 1, fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  subAmt: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm },

  // Health score
  healthHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: SPACING.sm },
  healthScore: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  healthScoreNum: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.lg, lineHeight: FONT_SIZE.lg + 2 },
  healthScoreOf: { fontFamily: FONT_FAMILY.body, fontSize: 9, color: COLORS.storm, lineHeight: 11 },
  healthRow: { gap: 4, marginBottom: SPACING.sm },
  healthLabelRow: { flexDirection: "row", justifyContent: "space-between" },
  healthLabel: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.ink },
  healthDesc: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  healthTrack: { height: 5, backgroundColor: SURFACE.track, borderRadius: RADIUS.full, overflow: "hidden" },
  healthFill: { height: 5, borderRadius: RADIUS.full },

  // Alert center
  alertEmpty: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm },
  alertRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm, paddingVertical: SPACING.xs },
  alertText: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, flex: 1 },

  // Weekly pattern
  weeklyPatternSummary: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  weeklyPatternPill: {
    flexGrow: 1,
    minWidth: 92,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.separator,
    gap: 3,
  },
  weeklyPatternPillLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  weeklyPatternPillValue: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  weeklyDayButton: {
    paddingHorizontal: 2,
    paddingTop: 2,
    borderRadius: RADIUS.sm,
  },
  weeklyDayButtonDisabled: {
    opacity: 0.45,
  },
  weeklyDayAmount: {
    maxWidth: "100%",
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: 9,
    color: COLORS.ink,
    textAlign: "center",
  },
  weeklyBar: {
    flex: 1,
    backgroundColor: COLORS.rosewood + "99",
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  weeklyDayCount: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 9,
    color: COLORS.storm,
    textAlign: "center",
  },

  // Transfer snapshot
  transferRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: SPACING.sm },
  transferRoute: { flex: 1, flexDirection: "row", alignItems: "center", gap: 4 },
  transferAcct: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.ink, flexShrink: 1 },
  transferRight: { alignItems: "flex-end", gap: 2, marginLeft: SPACING.sm },
  transferAmt: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  transferCount: { fontFamily: FONT_FAMILY.body, fontSize: 9, color: COLORS.textMuted },

  // Data quality
  dqRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm, paddingVertical: SPACING.xs },
  dqText: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.storm, flex: 1 },

  // Currency exposure
  currencyRow: { gap: SPACING.xs, marginBottom: SPACING.sm },
  currencyLabel: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  currencyDot: { width: 8, height: 8, borderRadius: 4 },
  currencyCode: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs, color: COLORS.ink },
  currencyPct: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, marginLeft: "auto" },
  currencyTrack: { height: 6, backgroundColor: SURFACE.track, borderRadius: RADIUS.full, overflow: "hidden" },
  currencyFill: { height: 6, borderRadius: RADIUS.full },

  // Period radar
  radarGrid: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.sm },
  radarItem: {
    width: "47%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
    gap: 3,
  },
  radarLabel: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  radarValue: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZE.sm, color: COLORS.ink },

  // Activity timeline
  timelineRow: { flexDirection: "row", alignItems: "flex-start", gap: SPACING.sm, paddingVertical: SPACING.sm },
  timelineContent: { flex: 1, gap: 2 },
  timelineDesc: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  timelineDate: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm },

  // Review inbox + command center + learning
  richEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.xs,
    paddingVertical: SPACING.lg,
  },
  richEmptyTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  richEmptyBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    textAlign: "center",
    lineHeight: 20,
  },
  reviewList: {
    gap: SPACING.sm,
  },
  reviewItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.card,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
  },
  reviewItemIconWrap: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewItemCopy: {
    flex: 1,
    gap: 2,
  },
  reviewItemTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  reviewItemBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  reviewItemRight: {
    alignItems: "center",
    gap: 4,
  },
  reviewItemCount: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  futureWindowList: {
    gap: SPACING.sm,
  },
  futureWindowCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.card,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    gap: SPACING.xs,
  },
  futureWindowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  futureWindowLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  futureWindowNet: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
  },
  futureWindowStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  futureWindowMeta: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  futureWindowBalance: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  futureWindowHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  learningTopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  learningMetricCard: {
    flex: 1,
    minWidth: "45%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.card,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    gap: 4,
  },
  learningMetricValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  learningMetricLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  phaseList: {
    gap: SPACING.sm,
  },
  phaseCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
    gap: SPACING.xs,
  },
  phaseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  phaseTitle: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  phasePct: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
  },
  phaseBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  phaseTrack: {
    height: 6,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.separator,
    overflow: "hidden",
  },
  phaseFill: {
    height: 6,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
  },
  learningInsightList: {
    gap: SPACING.xs,
    marginTop: SPACING.sm,
  },
  learningGroupTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    marginTop: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  learningSignalList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  learningSignalCard: {
    flex: 1,
    minWidth: "46%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(9,22,27,0.78)",
    borderWidth: 1,
    borderColor: COLORS.primary + "22",
    gap: SPACING.xs,
  },
  learningSignalCardWide: {
    minWidth: "100%",
    backgroundColor: "rgba(8,31,36,0.88)",
  },
  learningSignalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  learningSignalIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  learningSignalKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  learningSignalTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  learningSignalBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  learningInsightRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.xs,
  },
  learningInsightText: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 20,
  },
  commandActions: {
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  commandActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.card,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
  },
  commandActionCopy: {
    flex: 1,
    gap: 2,
  },
  suggestionRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  commandActionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  commandActionBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  commandMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  commandMetricCard: {
    flex: 1,
    minWidth: "45%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
    gap: 4,
  },
  commandMetricLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  commandMetricValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  commandMetricHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  readinessList: {
    gap: SPACING.sm,
  },
  readinessRow: {
    gap: SPACING.xs,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
  },
  readinessTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  readinessLabel: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  readinessStatus: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
  },
  readinessTrack: {
    height: 6,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.separator,
    overflow: "hidden",
  },
  readinessFill: {
    height: 6,
    borderRadius: RADIUS.full,
  },
  readinessDetail: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  commandRecommendation: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    marginTop: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.gold + "12",
    borderWidth: 1,
    borderColor: COLORS.gold + "22",
  },
  commandRecommendationText: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 20,
  },
  // Coach chips (U3)
  coachChipList: {
    gap: SPACING.xs,
    marginTop: SPACING.sm,
  },
  coachChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    borderLeftWidth: 2,
    paddingLeft: SPACING.sm,
    paddingVertical: 5,
  },
  coachChipText: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 18,
  },
  // Executive Summary delta chip (U1)
  executiveDeltaChip: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    marginTop: 3,
  },
  // Focus metric wide card (A3)
  focusMetricCardWide: {
    width: "100%",
  },
  // Preset situational subtitle (U4)
  presetSituationalText: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.gold,
    marginTop: SPACING.xs,
    lineHeight: 16,
  },
  // Advanced metrics section (N1-N5)
  advMetricSection: {
    paddingVertical: SPACING.sm,
    gap: SPACING.xs,
  },
  advMetricSectionBorder: {
    borderTopWidth: 0.5,
    borderTopColor: SURFACE.cardBorder,
    marginTop: SPACING.xs,
  },
  advMetricHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  advMetricTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  advMetricBadge: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
  },
  advMetricBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 16,
  },
  advMetricBarRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
    height: 48,
  },
  advMetricBarItem: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    justifyContent: "flex-end",
  },
  advMetricBar: {
    width: "100%",
    borderRadius: 3,
    minHeight: 4,
  },
  advMetricBarLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 9,
    color: COLORS.storm,
    textTransform: "capitalize",
  },
  advScoreBar: {
    height: 5,
    backgroundColor: SURFACE.card,
    borderRadius: 3,
    overflow: "hidden",
    marginTop: SPACING.xs,
  },
  advScoreFill: {
    height: "100%",
    borderRadius: 3,
  },
  layerKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: SPACING.xs,
  },
  layerHeroTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 18,
    color: COLORS.ink,
    marginBottom: SPACING.xs,
  },
  layerHeroBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.md,
    color: COLORS.storm,
    lineHeight: 28,
  },
  executiveIntro: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 21,
    marginBottom: SPACING.md,
  },
  executiveGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  executiveCard: {
    flex: 1,
    minWidth: "46%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(12,18,31,0.92)",
    borderWidth: 1,
    borderColor: SURFACE.softBorder,
    gap: SPACING.xs,
  },
  executiveCardWide: {
    minWidth: "100%",
  },
  executiveTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  executiveLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
  },
  executiveTonePill: {
    flexShrink: 1,
    maxWidth: "58%",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "18",
  },
  executiveTonePillWarning: {
    backgroundColor: COLORS.gold + "18",
  },
  executiveToneText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    flexShrink: 1,
  },
  executiveToneTextWarning: {
    color: COLORS.gold,
  },
  executiveValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 18,
    color: COLORS.ink,
  },
  executiveCaption: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 21,
  },
  aiSummaryShellWrap: {
    position: "relative",
    marginHorizontal: -SPACING.xs,
    borderRadius: RADIUS.xl,
  },
  aiSummaryGradientBorder: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: RADIUS.xl,
  },
  aiSummaryShell: {
    position: "relative",
    overflow: "hidden",
    borderRadius: RADIUS.xl,
    margin: 1.5,
    padding: SPACING.lg,
    backgroundColor: SURFACE.deepNavy,
    gap: SPACING.md,
  },
  aiSummaryAmbientGlow: {
    position: "absolute",
    borderRadius: 999,
    width: 100,
    height: 100,
  },
  aiSummaryAmbientGlowBlue: {
    top: -20,
    right: -10,
    backgroundColor: "rgba(92,141,255,0.10)",
  },
  aiSummaryAmbientGlowCoral: {
    bottom: -20,
    right: -10,
    backgroundColor: "rgba(255,125,141,0.08)",
  },
  aiSummaryAmbientGlowGold: {
    bottom: -20,
    left: -10,
    backgroundColor: "rgba(255,209,92,0.08)",
  },
  aiSummaryAmbientGlowTeal: {
    top: -20,
    left: -10,
    backgroundColor: "rgba(73,215,190,0.08)",
  },
  aiSummaryBadgeRow: {
    gap: SPACING.sm,
  },
  aiSummaryGeminiBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: SPACING.md,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.deepNavy,
    borderWidth: 1,
    borderColor: "rgba(73,215,190,0.30)",
  },
  aiSummaryGeminiDotsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  aiSummaryGeminiDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  aiSummaryGeminiBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.skyPale,
    letterSpacing: 0.3,
  },
  aiSummaryGeminiKicker: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: "rgba(223,231,245,0.72)",
    lineHeight: 18,
    maxWidth: 360,
  },
  aiSummaryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  aiSummaryHeaderText: {
    flex: 1,
    gap: SPACING.xs,
  },
  aiSummaryOrbWrap: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
  },
  aiSummaryPulseHalo: {
    position: "absolute",
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "rgba(73,215,190,0.12)",
    borderWidth: 1,
    borderColor: "rgba(73,215,190,0.28)",
  },
  aiSummaryIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE.deepNavy,
    borderWidth: 1.5,
    borderColor: "rgba(73,215,190,0.36)",
    shadowColor: EXTENDED_PALETTE.teal,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 20,
    elevation: 10,
  },
  aiSummaryIconRing: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(73,215,190,0.12)",
    borderWidth: 1,
    borderColor: "rgba(73,215,190,0.22)",
  },
  aiSummaryTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 19,
    color: COLORS.ink,
  },
  aiSummaryBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: "rgba(231,238,248,0.80)",
    lineHeight: 22,
  },
  aiSummarySelectorLabel: {
    marginTop: SPACING.xs,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: "rgba(198,210,227,0.78)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  aiSummaryToneRow: {
    marginTop: 10,
    flexDirection: "row",
    gap: SPACING.sm,
  },
  aiSummaryToneChip: {
    flex: 1,
    minHeight: 82,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.separator,
    gap: 6,
    overflow: "hidden",
  },
  aiSummaryToneChipActive: {
    backgroundColor: "rgba(92,141,255,0.12)",
    borderColor: "rgba(92,141,255,0.36)",
  },
  aiSummaryToneChipTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  aiSummaryToneChipTitleActive: {
    color: EXTENDED_PALETTE.skyPaler,
  },
  aiSummaryToneChipBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: "rgba(170,183,204,0.74)",
    lineHeight: 18,
  },
  aiSummaryToneChipBodyActive: {
    color: "rgba(240,245,255,0.88)",
  },
  aiSummaryButton: {
    marginTop: SPACING.md,
    minHeight: 54,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: SURFACE.deepNavy,
    borderWidth: 1.5,
    borderColor: "rgba(73,215,190,0.36)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: EXTENDED_PALETTE.teal,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 8,
  },
  aiSummaryButtonDisabled: {
    opacity: 0.6,
  },
  aiSummaryButtonAccent: {
    position: "absolute",
    top: -28,
    right: -18,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(73,215,190,0.12)",
  },
  aiSummaryButtonInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  aiSummaryButtonLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  aiSummaryHint: {
    marginTop: SPACING.md,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: "rgba(193,206,225,0.76)",
    lineHeight: 19,
  },
  aiSummaryResponseCard: {
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.md,
    paddingRight: SPACING.md,
    paddingLeft: SPACING.md + 4,
    borderRadius: RADIUS.lg,
    backgroundColor: SURFACE.deepNavy,
    borderWidth: 1,
    borderColor: "rgba(92,141,255,0.16)",
    overflow: "hidden",
    gap: SPACING.sm,
  },
  aiSummaryResponseGradientBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    borderTopLeftRadius: RADIUS.lg,
    borderBottomLeftRadius: RADIUS.lg,
  },
  aiSummaryResponseAiTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  aiSummaryResponseLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.mintLight,
    letterSpacing: 0.4,
  },
  aiSummaryGlossaryHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 12,
    color: "rgba(180,216,255,0.76)",
    lineHeight: 18,
  },
  aiSummaryResponseText: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: "rgba(230,240,255,0.92)",
    lineHeight: 22,
  },
  aiSummaryResponseTerm: {
    color: EXTENDED_PALETTE.mintLighter,
    textDecorationLine: "underline",
    textDecorationColor: "rgba(73,215,190,0.65)",
    backgroundColor: "rgba(73,215,190,0.12)",
  },
  aiSummaryTermSheet: {
    gap: SPACING.md,
  },
  aiSummaryTermSheetBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(73,215,190,0.10)",
    borderWidth: 1,
    borderColor: "rgba(73,215,190,0.20)",
  },
  aiSummaryTermSheetBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.mintLight,
  },
  aiSummaryTermSheetTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.xl,
    color: COLORS.ink,
  },
  aiSummaryTermSheetBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.md,
    color: "rgba(230,240,255,0.88)",
    lineHeight: 24,
  },
  aiSummaryFooterRow: {
    paddingTop: 2,
  },
  aiSummaryFooterText: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 12,
    color: "rgba(169,184,205,0.68)",
    lineHeight: 18,
  },
  executiveModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(5,8,18,0.82)",
    padding: SPACING.md,
  },
  executiveModalCard: {
    borderRadius: RADIUS.xl,
    backgroundColor: EXTENDED_PALETTE.indigoBg,
    borderWidth: 1,
    borderColor: SURFACE.inputBorder,
    padding: SPACING.lg,
    gap: SPACING.md,
  },
  executiveModalHandle: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  executiveModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  executiveModalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE.cardBorder,
  },
  executiveModalTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 20,
    color: COLORS.ink,
  },
  executiveModalSummary: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  movementPreviewOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(5,8,18,0.72)",
    padding: SPACING.md,
  },
  movementPreviewBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  movementPreviewCard: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "82%",
    borderRadius: RADIUS.xl,
    backgroundColor: EXTENDED_PALETTE.indigoBg,
    borderWidth: 1,
    borderColor: SURFACE.inputBorder,
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  movementPreviewHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  movementPreviewKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  movementPreviewTitle: {
    marginTop: 3,
    fontFamily: FONT_FAMILY.heading,
    fontSize: 20,
    color: COLORS.ink,
  },
  movementPreviewClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE.cardBorder,
  },
  movementPreviewSubtitle: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 22,
  },
  movementPreviewScope: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  movementPreviewSuggestionAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.primary + "18",
    borderWidth: 1,
    borderColor: COLORS.primary + "38",
  },
  movementPreviewSuggestionActionDisabled: {
    opacity: 0.64,
  },
  movementPreviewSuggestionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  movementPreviewSuggestionBody: {
    marginTop: 2,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  movementPreviewStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  movementPreviewStatPill: {
    minWidth: 104,
    flexGrow: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 9,
    borderRadius: RADIUS.lg,
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
  },
  movementPreviewStatLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  movementPreviewStatValue: {
    marginTop: 2,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  movementPreviewList: {
    marginTop: SPACING.xs,
  },
  movementPreviewListContent: {
    gap: SPACING.sm,
    paddingBottom: SPACING.xs,
  },
  movementPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.separator,
  },
  movementPreviewRowTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  movementPreviewRowMeta: {
    marginTop: 3,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  movementPreviewRowStatus: {
    marginTop: 2,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textMuted,
  },
  movementPreviewRowSide: {
    width: 118,
    alignItems: "flex-end",
    gap: SPACING.xs,
  },
  movementPreviewAmount: {
    maxWidth: 118,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
  },
  movementPreviewEditBtn: {
    minWidth: 72,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "24",
    borderWidth: 1,
    borderColor: COLORS.primary + "42",
  },
  movementPreviewEditText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
  },
  movementPreviewEmpty: {
    paddingVertical: SPACING.xl,
    gap: SPACING.xs,
  },
  movementPreviewEmptyTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
    textAlign: "center",
  },
  movementPreviewEmptyBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 21,
    textAlign: "center",
  },
  explanationSheetContent: {
    gap: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  explanationIntroCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.separator,
    gap: SPACING.xs,
  },
  explanationKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  explanationSummary: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 23,
  },
  explanationVisualCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(9,22,27,0.82)",
    borderWidth: 1,
    borderColor: COLORS.primary + "1F",
    gap: SPACING.md,
  },
  explanationVisualHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  explanationVisualTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  explanationVisualHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
    marginTop: 2,
  },
  explanationVisualGrid: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  explanationVisualMetric: {
    flex: 1,
    gap: 5,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: SURFACE.subtle,
  },
  explanationVisualMetricLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  explanationVisualMetricValue: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
  },
  explanationVisualTrack: {
    height: 5,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.09)",
    overflow: "hidden",
  },
  explanationVisualFill: {
    height: 5,
    borderRadius: RADIUS.full,
  },
  explanationSectionCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(8,13,24,0.72)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.075)",
    gap: SPACING.md,
  },
  explanationSectionCardCollapsed: {
    backgroundColor: "rgba(8,13,24,0.48)",
  },
  explanationSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  explanationStepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary + "16",
    borderWidth: 1,
    borderColor: COLORS.primary + "22",
  },
  explanationStepBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
  },
  explanationSectionTitle: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  explanationChevron: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    transform: [{ rotate: "0deg" }],
  },
  explanationChevronOpen: {
    transform: [{ rotate: "90deg" }],
  },
  explanationBulletList: {
    gap: SPACING.sm,
  },
  explanationBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  explanationBulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 8,
    backgroundColor: COLORS.primary,
  },
  explanationBulletDotMuted: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.42)",
  },
  explanationBulletText: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  explanationCollapsedHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 21,
  },
  explanationResultSection: {
    gap: SPACING.md,
  },
  explanationActionsSection: {
    marginTop: SPACING.xs,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.09)",
    gap: SPACING.md,
  },
  explanationActionsTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  executiveModalSection: {
    gap: SPACING.xs,
  },
  executiveModalSectionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  executiveModalBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  resultMeaningCard: {
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
  },
  resultMeaningHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  resultMeaningIndicator: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  resultMeaningIndicatorPositive: {
    backgroundColor: COLORS.primary,
  },
  resultMeaningIndicatorWarning: {
    backgroundColor: COLORS.gold,
  },
  resultMeaningIndicatorDanger: {
    backgroundColor: EXTENDED_PALETTE.rosePink,
  },
  resultMeaningCardPositive: {
    backgroundColor: "rgba(18,48,40,0.92)",
    borderColor: COLORS.primary + "18",
  },
  resultMeaningCardWarning: {
    backgroundColor: "rgba(44,34,20,0.94)",
    borderColor: "rgba(215,190,123,0.22)",
  },
  resultMeaningCardDanger: {
    backgroundColor: "rgba(52,22,33,0.94)",
    borderColor: "rgba(218,122,154,0.22)",
  },
  resultMeaningTone: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  resultMeaningTonePositive: {
    color: COLORS.primary,
  },
  resultMeaningToneWarning: {
    color: COLORS.gold,
  },
  resultMeaningToneDanger: {
    color: EXTENDED_PALETTE.rosePink,
  },
  executiveActionList: {
    gap: SPACING.sm,
  },
  executiveActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(59,166,142,0.24)",
    borderWidth: 1,
    borderColor: COLORS.primary + "26",
  },
  executiveActionBtnText: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  panelKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.gold,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: SPACING.xs,
  },
  panelTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 18,
    color: COLORS.ink,
    marginBottom: SPACING.xs,
  },
  panelBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
    marginBottom: SPACING.md,
  },
  panelCoachCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(31,27,18,0.94)",
    borderWidth: 1,
    borderColor: "rgba(215,190,123,0.24)",
    gap: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  panelCoachTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  panelCoachIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(215,190,123,0.14)",
  },
  panelCoachCopy: { flex: 1, gap: 2 },
  panelCoachLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.gold,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  panelCoachTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  panelCoachPill: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(215,190,123,0.12)",
  },
  panelCoachPillText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.gold,
  },
  panelCoachBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    lineHeight: 24,
  },
  miniChip: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.softBorder,
  },
  miniChipText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
  },
  panelCoachFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  panelCoachFooterText: {
    flex: 1,
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
  },
  panelApplyBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(215,190,123,0.24)",
  },
  panelApplyBtnText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.gold,
  },
  presetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
    flexWrap: "wrap",
  },
  presetTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  presetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  presetCard: {
    width: "48%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(12,18,31,0.90)",
    borderWidth: 1,
    borderColor: SURFACE.softBorder,
    gap: SPACING.xs,
  },
  presetCardActive: {
    borderColor: COLORS.primary + "88",
    backgroundColor: COLORS.primary + "10",
  },
  presetCardWide: {
    width: "100%",
  },
  presetCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.xs,
  },
  presetCardTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.ink,
    flex: 1,
    flexShrink: 1,
  },
  presetBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.gold + "18",
    flexShrink: 0,
  },
  presetBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.gold,
  },
  presetCardBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  widgetPanelCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(12,18,31,0.90)",
    borderWidth: 1,
    borderColor: SURFACE.softBorder,
    gap: SPACING.sm,
  },
  widgetPanelTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.ink,
  },
  widgetPanelBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  widgetPanelHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  widgetChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  widgetChip: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.09)",
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
  },
  widgetChipText: {
    fontFamily: FONT_FAMILY.bodyMedium,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
  },
  howList: { gap: SPACING.md, marginTop: SPACING.md },
  howItem: { gap: 4 },
  howTitle: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.lg, color: COLORS.ink },
  howBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm, lineHeight: 22 },
  focusHeroCard: {
    marginTop: SPACING.md,
    padding: SPACING.lg,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(16,34,31,0.94)",
    borderWidth: 1,
    borderColor: COLORS.primary + "22",
    gap: SPACING.md,
  },
  focusHeroTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  focusHeroLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  focusHeroPills: {
    flexShrink: 1,
    maxWidth: "48%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 6,
  },
  focusHeroTonePill: {
    maxWidth: "100%",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "14",
  },
  focusHeroToneText: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs, color: EXTENDED_PALETTE.skySoft },
  focusHeroTonePillMuted: {
    maxWidth: "100%",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.softBorder,
  },
  focusHeroToneTextMuted: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs, color: COLORS.storm },
  focusHeroMiddle: { flexDirection: "row", alignItems: "center", gap: SPACING.md },
  focusHeroTitle: { fontFamily: FONT_FAMILY.heading, fontSize: 18, color: COLORS.ink },
  focusHeroValue: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: 18, color: COLORS.ink, lineHeight: 28 },
  focusHeroBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.md, color: COLORS.storm, lineHeight: 26 },
  focusHeroReason: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.primary,
    lineHeight: 20,
  },
  scopeHint: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
    marginBottom: SPACING.sm,
  },
  focusMetricGrid: { flexDirection: "row", gap: SPACING.sm, marginTop: SPACING.md },
  focusMetricCard: {
    flex: 1,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(12,18,31,0.90)",
    borderWidth: 1,
    borderColor: SURFACE.softBorder,
    gap: SPACING.xs,
  },
  focusMetricLabel: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm },
  focusMetricValue: { fontFamily: FONT_FAMILY.heading, fontSize: 18, color: COLORS.ink },
  focusMetricHint: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm, lineHeight: 22 },
  layerSection: {
    gap: SPACING.xs,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(8,13,24,0.58)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
    borderLeftWidth: 2,
    borderLeftColor: COLORS.primary + "88",
  },
  layerSectionKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  layerSectionTitle: { fontFamily: FONT_FAMILY.heading, fontSize: 20, color: COLORS.ink },
  layerSectionBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm, lineHeight: 20, flex: 1 },
  layerBulletList: { gap: 5, marginTop: 8 },
  layerBulletRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  layerBulletDot: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.sm, color: COLORS.pine, lineHeight: 20 },
  visualChartKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  visualChartIntro: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.sm,
    color: COLORS.storm,
    lineHeight: 22,
  },
  visualChartFootnote: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  visualChartAction: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "14",
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
  },
  annualHeaderRow: {
    gap: SPACING.sm,
  },
  annualYearList: {
    gap: SPACING.xs,
    paddingRight: SPACING.sm,
  },
  annualYearPill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: SURFACE.separator,
  },
  annualYearPillActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  annualYearText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  annualYearTextActive: {
    color: EXTENDED_PALETTE.greenInk,
  },
  annualSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  annualSummaryCard: {
    width: "48%",
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.075)",
    gap: 4,
  },
  annualSummaryValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 17,
  },
  annualFlowChart: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 5,
    paddingTop: SPACING.xs,
  },
  annualMonthCol: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  annualMonthColMuted: {
    opacity: 0.28,
  },
  annualBarsBox: {
    width: "100%",
    height: 74,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 2,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255,255,255,0.035)",
    paddingHorizontal: 2,
    paddingBottom: 2,
  },
  annualFlowBar: {
    flex: 1,
    maxWidth: 7,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  annualNetList: {
    gap: SPACING.xs,
  },
  annualNetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  annualNetMonth: {
    width: 34,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textTransform: "capitalize",
  },
  annualNetTrack: {
    flex: 1,
    height: 8,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.track,
    overflow: "hidden",
  },
  annualNetFill: {
    height: 8,
    borderRadius: RADIUS.full,
  },
  annualNetAmount: {
    width: 88,
    textAlign: "right",
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
  },
  annualDetailContent: {
    gap: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  annualDetailHero: {
    gap: SPACING.xs,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.separator,
  },
  annualDetailTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 20,
    color: COLORS.ink,
  },
  annualDetailMini: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  annualDetailSection: {
    gap: SPACING.sm,
  },
  annualDetailSectionTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  annualDetailCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(9,22,27,0.78)",
    borderWidth: 1,
    borderColor: COLORS.primary + "22",
  },
  annualDetailCategoryName: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
  },
  annualDetailCategoryAmount: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.expense,
    textAlign: "right",
  },
  annualMovementRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.track,
  },
  annualMovementTitle: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  annualMovementMeta: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    marginTop: 2,
  },
  annualMovementAmount: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    textAlign: "right",
  },
  annualDetailActions: {
    gap: SPACING.sm,
    paddingTop: SPACING.sm,
  },
  annualDetailPrimaryBtn: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
  },
  annualDetailPrimaryBtnText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.md,
    color: EXTENDED_PALETTE.greenInk,
  },
  annualDetailSplitActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  annualDetailSecondaryBtn: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
  },
  annualDetailSecondaryBtnText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  bridgeChartStack: {
    gap: SPACING.md,
  },
  bridgeRow: {
    gap: SPACING.xs,
  },
  bridgeRowHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  bridgeLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  bridgeDetail: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  bridgeAmount: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    textAlign: "right",
  },
  bridgeTrack: {
    position: "relative",
    height: 12,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.track,
    overflow: "hidden",
  },
  bridgeAxis: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 1,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  bridgeFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    borderRadius: RADIUS.full,
  },
  savingsSparkWrap: {
    alignItems: "center",
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  savingsStatsRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.xl,
  },
  savingsStatCard: {
    flex: 1,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    backgroundColor: SURFACE.subtle,
    borderWidth: 1,
    borderColor: SURFACE.track,
    gap: 3,
  },
  savingsStatLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  savingsStatValue: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
  },
  netBarsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  netBarsCol: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  netBarsBox: {
    position: "relative",
    width: "100%",
    height: 68,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255,255,255,0.035)",
    overflow: "hidden",
  },
  netBarsAxis: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 34,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  netBar: {
    position: "absolute",
    left: "24%",
    right: "24%",
    borderRadius: 5,
  },
  netBarPositive: {
    backgroundColor: COLORS.income + "cc",
  },
  netBarNegative: {
    backgroundColor: COLORS.expense + "cc",
  },
  donutChartBody: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  donutWrap: {
    width: 132,
    height: 132,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  donutCenter: {
    position: "absolute",
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    backgroundColor: SURFACE.deepNavy,
    borderWidth: 1,
    borderColor: SURFACE.track,
  },
  donutCenterValue: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 18,
    color: COLORS.ink,
  },
  donutCenterLabel: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    maxWidth: 58,
    textAlign: "center",
  },
  donutLegend: {
    flex: 1,
    gap: SPACING.sm,
  },
  donutLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  donutLegendDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  donutLegendName: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  donutLegendPct: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  donutLegendAmount: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.ink,
    textAlign: "right",
  },
  qualityHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  qualityActions: {
    alignItems: "flex-end",
    gap: SPACING.xs,
  },
  cardHeaderWithAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  inlineExplainBtn: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: SURFACE.cardBorder,
    borderWidth: 1,
    borderColor: SURFACE.inputBorder,
  },
  inlineExplainBtnText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
  },
  qualityKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.lavenderInk,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  qualityTitle: { fontFamily: FONT_FAMILY.heading, fontSize: 18, color: COLORS.ink },
  qualityBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm, lineHeight: 22 },
  qualityToggleBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary + "18",
  },
  qualityToggleBtnText: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.sm, color: COLORS.primary },
  projectionStack: { gap: SPACING.sm },
  projectionCard: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(12,18,31,0.90)",
    borderWidth: 1,
    borderColor: SURFACE.softBorder,
    gap: SPACING.sm,
  },
  projectionTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.sm },
  projectionLabel: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, textTransform: "uppercase", letterSpacing: 0.5 },
  projectionTitle: { fontFamily: FONT_FAMILY.heading, fontSize: 18, color: COLORS.ink },
  projectionBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.storm, lineHeight: 24 },
  projectionFormulaBox: {
    padding: SPACING.md,
    borderRadius: RADIUS.xl,
    backgroundColor: "rgba(5,10,18,0.58)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    gap: SPACING.sm,
  },
  projectionFormulaHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  projectionFormulaKicker: {
    flex: 1,
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  projectionFormulaTotal: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.md,
    color: COLORS.ink,
    textAlign: "right",
  },
  projectionFormulaSummary: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  projectionFormulaRows: {
    gap: 8,
  },
  projectionFormulaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  projectionFormulaCopy: {
    flex: 1,
    gap: 2,
  },
  projectionFormulaLabel: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },
  projectionFormulaDetail: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 17,
  },
  projectionFormulaAmount: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
    textAlign: "right",
  },
  projectionFormulaAmountPositive: {
    color: COLORS.income,
  },
  projectionFormulaAmountNegative: {
    color: COLORS.expense,
  },
  projectionFormulaEquals: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.primary + "26",
  },
  projectionFormulaEqualsText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.primary,
  },
  projectionFormulaEqualsAmount: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: FONT_SIZE.lg,
    color: COLORS.primary,
  },
  projectionScenarioStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  projectionScenarioText: {
    flexGrow: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.06)",
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    textAlign: "center",
  },
  actionPillRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  actionPillBody: { flex: 1, fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.ink, lineHeight: 22 },
  actionPill: { paddingHorizontal: SPACING.sm, paddingVertical: 6, borderRadius: RADIUS.full, backgroundColor: COLORS.primary + "18" },
  actionPillText: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.sm, color: COLORS.primary },
  anomalyList: { gap: SPACING.sm, marginBottom: SPACING.md },
  anomalyCard: { padding: SPACING.md, borderRadius: RADIUS.xl, gap: SPACING.sm, borderWidth: 1 },
  anomalyCardStrong: { backgroundColor: "rgba(52,22,33,0.96)", borderColor: "rgba(218,122,154,0.22)" },
  anomalyCardReview: { backgroundColor: "rgba(37,31,19,0.96)", borderColor: "rgba(215,190,123,0.20)" },
  anomalyTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.sm },
  anomalyTitle: { flex: 1, fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.lg, color: COLORS.ink },
  anomalyBadge: { paddingHorizontal: SPACING.sm, paddingVertical: 5, borderRadius: RADIUS.full },
  anomalyBadgeStrong: { backgroundColor: "rgba(218,122,154,0.16)" },
  anomalyBadgeReview: { backgroundColor: "rgba(215,190,123,0.16)" },
  anomalyBadgeText: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },
  anomalyBadgeTextStrong: { color: EXTENDED_PALETTE.rosePink },
  anomalyBadgeTextReview: { color: COLORS.gold },
  anomalyBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: COLORS.ink, lineHeight: 24 },
  anomalyBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.sm },
  anomalyMeta: { flex: 1, fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, lineHeight: 18 },
  secondaryOutlineBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: SURFACE.cardBorder,
    backgroundColor: SURFACE.separator,
  },
  secondaryOutlineBtnText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.ink,
  },

  // Accounts breakdown ring
  breakdownWrap: { flexDirection: "row", alignItems: "center", gap: SPACING.lg },
  breakdownLegend: { flex: 1, gap: SPACING.xs + 1 },
  breakdownItem: { flexDirection: "row", alignItems: "center", gap: SPACING.xs },
  breakdownDot: { width: 8, height: 8, borderRadius: 4, flexShrink: 0 },
  breakdownName: { flex: 1, fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.xs, color: COLORS.ink },
  breakdownPct: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },

  // Savings trend sparkline
  trendHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: SPACING.xs },
  trendBadge: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },
  trendBody: { flexDirection: "row", alignItems: "center", gap: SPACING.md },
  trendLegend: { flex: 1, gap: 3 },
  trendRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  trendLabel: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, textTransform: "capitalize" },
  trendNet: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.xs },

  // Pro gate
  proGate: {
    gap: SPACING.md,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    backgroundColor: "rgba(215,190,123,0.06)",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "rgba(215,190,123,0.18)",
  },
  proGateHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.md,
  },
  proGateIconWrap: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(215,190,123,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  proGateIconWrapLg: {
    width: 42,
    height: 42,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(215,190,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  proGateText: { flex: 1, gap: 2 },
  proGateTitle: { fontFamily: FONT_FAMILY.bodyMedium, fontSize: FONT_SIZE.sm, color: COLORS.ink },
  proGateTitleLg: { fontFamily: FONT_FAMILY.bodySemibold, fontSize: FONT_SIZE.md, color: COLORS.ink },
  proGateBody: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: COLORS.storm, lineHeight: 16 },
  proGateBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(215,190,123,0.12)",
    borderWidth: 1,
    borderColor: "rgba(215,190,123,0.35)",
  },
  proGateBadgeMuted: {
    backgroundColor: "rgba(150,162,181,0.10)",
    borderColor: "rgba(150,162,181,0.20)",
  },
  proGateBadgeText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: 10,
    color: COLORS.gold,
    letterSpacing: 0.8,
  },
  proGateFeatures: {
    gap: SPACING.xs,
    paddingTop: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: "rgba(215,190,123,0.10)",
  },
  proGateFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  proGateFeatureText: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 18,
  },
  advancedGiftCard: {
    overflow: "hidden",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.xl,
    backgroundColor: EXTENDED_PALETTE.wineDeep,
    borderWidth: 1,
    borderColor: "rgba(255,205,214,0.38)",
  },
  advancedGiftHeartsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
  },
  advancedGiftHeart: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 34,
    color: EXTENDED_PALETTE.rosePaleBg,
    lineHeight: 38,
  },
  advancedGiftHeartSmall: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 22,
    color: EXTENDED_PALETTE.rosePinkSoft,
    lineHeight: 28,
  },
  advancedGiftKicker: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.rosePale,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  advancedGiftTitle: {
    fontFamily: FONT_FAMILY.heading,
    fontSize: 25,
    color: EXTENDED_PALETTE.white,
    lineHeight: 32,
    textAlign: "center",
  },
  advancedGiftBody: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.md,
    color: EXTENDED_PALETTE.rosePaleBgSoft,
    lineHeight: 23,
    textAlign: "center",
  },
  advancedGiftPill: {
    marginTop: SPACING.xs,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.26)",
  },
  advancedGiftPillText: {
    fontFamily: FONT_FAMILY.bodySemibold,
    fontSize: FONT_SIZE.xs,
    color: EXTENDED_PALETTE.white,
  },

  // Interpretation lines — one sentence per metric telling the user what the number means
  executiveInterpret: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    lineHeight: 16,
    marginTop: 3,
  },
  healthScoreInterpret: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    color: COLORS.storm,
    lineHeight: 16,
  },
  healthInterpret: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    lineHeight: 15,
    marginTop: 3,
  },
  advMetricInterpret: {
    fontFamily: FONT_FAMILY.body,
    fontSize: FONT_SIZE.xs,
    lineHeight: 16,
    marginTop: 4,
  },
});
