-- Tipo de gasto: necesidades, deseos, ahorros.
--
-- Una maestra por espacio de trabajo, como categorías o contactos. Responde a una pregunta que
-- la categoría no puede responder: "Alimentación" dice EN QUÉ se fue la plata, no si hacía falta.
--
-- **Dónde vive el dato.** En los dos sitios, y por una razón medida: de las 20 categorías de
-- gasto reales, las dos con más movimientos son mixtas — Alimentación (221 movimientos) es
-- mercado y también cena fuera; Transporte (172) es la moto al trabajo y también el taxi para
-- salir. Con el tipo solo en la categoría, el 65 % de los movimientos quedaría mal la mitad de
-- las veces; solo en el movimiento, serían cientos de preguntas al año.
--
-- Así que la categoría trae un tipo **por defecto** que rellena el formulario, y el movimiento
-- puede llevar el suyo cuando toque. Al calcular, el tipo efectivo es
-- `movements.spend_type_id` y, si está vacío, el de su categoría: las métricas funcionan en
-- cuanto se configuran los defaults, sin re-etiquetar el historial.

create table if not exists public.spend_types (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  created_by_user_id uuid references auth.users(id) on delete set null,
  updated_by_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  color text,
  icon text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dos tipos con el mismo nombre en un espacio no distinguen nada, y al elegir en una lista se
-- convierten en dos filas idénticas.
create unique index if not exists spend_types_workspace_name_unique
  on public.spend_types (workspace_id, lower(name));

create index if not exists idx_spend_types_workspace
  on public.spend_types (workspace_id) where is_active;

alter table public.spend_types enable row level security;

do $$
begin
  if not exists (select 1 from pg_policy where polname = 'spend_types_member_select') then
    create policy spend_types_member_select on public.spend_types
      for select using (is_workspace_member(workspace_id));
  end if;
  if not exists (select 1 from pg_policy where polname = 'spend_types_member_insert') then
    create policy spend_types_member_insert on public.spend_types
      for insert with check (is_workspace_member(workspace_id));
  end if;
  if not exists (select 1 from pg_policy where polname = 'spend_types_member_update') then
    create policy spend_types_member_update on public.spend_types
      for update using (is_workspace_member(workspace_id));
  end if;
  if not exists (select 1 from pg_policy where polname = 'spend_types_member_delete') then
    create policy spend_types_member_delete on public.spend_types
      for delete using (is_workspace_member(workspace_id));
  end if;
end $$;

-- El defecto que rellena el formulario al elegir categoría.
alter table public.categories
  add column if not exists default_spend_type_id bigint
  references public.spend_types(id) on delete set null;

-- Y el del movimiento, que manda cuando está puesto.
-- `on delete set null`: borrar un tipo no puede borrar movimientos ni dejarlos apuntando a nada.
alter table public.movements
  add column if not exists spend_type_id bigint
  references public.spend_types(id) on delete set null;

create index if not exists idx_movements_spend_type
  on public.movements (workspace_id, spend_type_id) where spend_type_id is not null;

comment on table public.spend_types is
  'Maestra de tipos de gasto por espacio (necesidades, deseos, ahorros). La categoría dice en qué '
  'se fue la plata; el tipo, si hacía falta. Solo aplica a gastos.';
comment on column public.categories.default_spend_type_id is
  'Tipo que se propone al elegir esta categoría en el formulario. El movimiento puede cambiarlo.';
comment on column public.movements.spend_type_id is
  'Tipo de gasto de ESTE movimiento. Vacío = hereda el de su categoría al calcular métricas.';
