-- Plantillas de movimientos: prellenan el formulario con un tap (backlog P3).
-- Se crean desde el detalle de un movimiento ("Guardar como plantilla") y se
-- usan desde el quick-add del FAB.

create table if not exists public.movement_templates (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces (id) on delete cascade,
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  movement_type text not null check (movement_type in ('expense', 'income', 'transfer')),
  source_account_id bigint references public.accounts (id) on delete set null,
  destination_account_id bigint references public.accounts (id) on delete set null,
  source_amount numeric(14, 2),
  destination_amount numeric(14, 2),
  category_id bigint references public.categories (id) on delete set null,
  counterparty_id bigint references public.counterparties (id) on delete set null,
  description text not null default '',
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists movement_templates_workspace_idx
  on public.movement_templates (workspace_id, sort_order, id);

alter table public.movement_templates enable row level security;

create policy movement_templates_member_select on public.movement_templates
  for select using (is_workspace_member(workspace_id));
create policy movement_templates_member_insert on public.movement_templates
  for insert with check (is_workspace_member(workspace_id));
create policy movement_templates_member_update on public.movement_templates
  for update using (is_workspace_member(workspace_id)) with check (is_workspace_member(workspace_id));
create policy movement_templates_member_delete on public.movement_templates
  for delete using (is_workspace_member(workspace_id));
